-- +goose Up
-- The eighth deck_access permission (#207): read and resolve flagged-card feedback on THIS deck.
-- Independent of can_view_progress -- that flag is deliberately scoped to aggregate-only reads
-- of user_card_state/review_log (#87, docs/schema.md); a named student's comment is
-- individual-level disclosure and doesn't fit that scope, so it gets its own flag rather than
-- riding on can_view_progress. No last-holder guard, same reasoning as can_view_progress: a deck
-- with zero holders of this flag is not stranded, it simply has no one reviewing feedback.
ALTER TABLE deck_access ADD COLUMN can_view_flags boolean NOT NULL DEFAULT false;

-- A student's feedback on one card, addressed to whoever holds can_view_flags on its deck.
-- card_id CASCADEs (unlike review_log.card_id, which has no FK by decision, docs/schema.md):
-- a flag has no protected-training-data status (CLAUDE.md §2.5 doesn't apply here), so when its
-- card is deleted or regenerated by a note edit, the simplest thing is for the flag to go with
-- it -- if the edit fixed the reported problem, the flag's job is already done.
CREATE TABLE card_flags (
    id                  uuid PRIMARY KEY DEFAULT uuidv7(),
    card_id             uuid NOT NULL REFERENCES cards (id) ON DELETE CASCADE,
    deck_id             uuid NOT NULL REFERENCES decks (id) ON DELETE CASCADE, -- denormalised: lets
                        -- the flags-list/count queries filter by deck without a join through cards
    flagged_by_user_id  uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    comment             text NOT NULL,
    status              text NOT NULL DEFAULT 'open', -- 'open' | 'resolved' (internal/db/flags.go)
    created_at          timestamptz NOT NULL DEFAULT now(),
    resolved_at         timestamptz,
    resolved_by_user_id uuid REFERENCES users (id) ON DELETE SET NULL
);

-- One open flag per (user, card): resubmitting while one is still open replaces it (UpsertCardFlag,
-- flags.sql) instead of piling up duplicates from the same student on the same card.
CREATE UNIQUE INDEX card_flags_open_idx ON card_flags (card_id, flagged_by_user_id) WHERE status = 'open';
-- The flags-list page's main filter: all open (or all resolved) flags for one deck.
CREATE INDEX card_flags_deck_status_idx ON card_flags (deck_id, status);

-- +goose Down
DROP TABLE card_flags;
ALTER TABLE deck_access DROP COLUMN can_view_flags;
