// Command gen-accents regenerates web/static/accents.css (#267): one override block per accent
// colour, holding only the custom properties where Pico's stock pico.<colour>.min.css differs
// from the default (azure) pico.min.css we vendor. Values are Pico's own, copied, never invented.
//
// Usage (repo root): go run ./scripts/gen-accents
// Re-run after bumping the vendored Pico version (web/static/README.md); keep picoVersion and
// accents in sync with accentOptions in internal/http/settings.go and migration 00025.
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
)

const picoVersion = "2.1.1"

// accents are the non-default colours offered; azure is Pico's default and needs no block.
var accents = []string{"blue", "indigo", "purple", "pink", "red", "orange", "green"}

// block is one of Pico's three theme blocks; sel is where our override applies. Neither
// override targets bare [data-theme=light]/[data-theme=dark] descendants of <html>, so the
// light-surface card stage (#268) keeps Pico's default palette and note-type CSS is unaffected.
type block struct {
	name   string
	marker string // distinguishes the block in Pico's minified output
	sel    string // %s = accent name
	media  bool
}

var blocks = []block{
	{"light", ":root:not([data-theme=dark]),[data-theme=light]{", `:root[data-accent="%s"]:not([data-theme=dark])`, false},
	{"auto-dark", ":root:not([data-theme]){", `:root[data-accent="%s"]:not([data-theme])`, true},
	{"dark", "[data-theme=dark]{", `:root[data-accent="%s"][data-theme=dark]`, false},
}

var propRe = regexp.MustCompile(`(--pico-[a-z-]+):([^;}]+)`)

// props returns the custom properties declared in the block of css that starts at marker.
func props(css string, b block) (map[string]string, []string, error) {
	i := strings.Index(css, b.marker)
	if i < 0 {
		return nil, nil, fmt.Errorf("block %q not found", b.name)
	}
	rest := css[i+len(b.marker):]
	end := strings.Index(rest, "}")
	if end < 0 {
		return nil, nil, fmt.Errorf("block %q unterminated", b.name)
	}
	m := map[string]string{}
	var order []string
	for _, p := range propRe.FindAllStringSubmatch(rest[:end], -1) {
		m[p[1]] = p[2]
		order = append(order, p[1])
	}
	return m, order, nil
}

func fetch(url string) (string, error) {
	resp, err := http.Get(url) //nolint:gosec,noctx // dev-time script, fixed pinned URL
	if err != nil {
		return "", err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("%s: %s", url, resp.Status)
	}
	b, err := io.ReadAll(resp.Body)
	return string(b), err
}

func run() error {
	base, err := os.ReadFile("web/static/pico.min.css")
	if err != nil {
		return err
	}
	var out strings.Builder
	fmt.Fprintf(&out, "/* GENERATED by scripts/gen-accents from Pico %s pico.<colour>.min.css (#267) -- do not edit.\n", picoVersion)
	out.WriteString("   Only the properties that differ from the default (azure) palette; selectors sit on <html>\n")
	out.WriteString("   so the light-surface card stage keeps Pico's defaults. */\n")
	// Settings-page swatches use the light-mode button colour, azure (the default) included.
	defs := make([]map[string]string, len(blocks))
	for i, b := range blocks {
		if defs[i], _, err = props(string(base), b); err != nil {
			return fmt.Errorf("default: %w", err)
		}
	}
	swatches := map[string]string{"azure": defs[0]["--pico-primary-background"]}
	for _, a := range accents {
		css, err := fetch(fmt.Sprintf("https://cdn.jsdelivr.net/npm/@picocss/pico@%s/css/pico.%s.min.css", picoVersion, a))
		if err != nil {
			return err
		}
		for i, b := range blocks {
			def := defs[i]
			got, order, err := props(css, b)
			if err != nil {
				return fmt.Errorf("%s: %w", a, err)
			}
			if b.name == "light" {
				swatches[a] = got["--pico-primary-background"]
			}
			var decls []string
			for _, k := range order {
				if got[k] != def[k] {
					decls = append(decls, k+":"+got[k])
				}
			}
			if len(decls) == 0 {
				return fmt.Errorf("%s/%s: no differing properties; Pico layout changed?", a, b.name)
			}
			rule := fmt.Sprintf(b.sel, a) + "{" + strings.Join(decls, ";") + "}"
			if b.media {
				rule = "@media only screen and (prefers-color-scheme:dark){" + rule + "}"
			}
			out.WriteString(rule + "\n")
		}
	}
	for _, a := range append([]string{"azure"}, accents...) {
		fmt.Fprintf(&out, ".accent-swatch[data-accent=\"%s\"]{background:%s}\n", a, swatches[a])
	}
	return os.WriteFile("web/static/accents.css", []byte(out.String()), 0o644) //nolint:gosec // static asset, world-readable
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-accents:", err)
		os.Exit(1)
	}
}
