// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendNoteFieldSlot = `-- name: AppendNoteFieldSlot :execrows
UPDATE notes SET fields = fields || '""'::jsonb, modified_at = now() WHERE note_type_id = $1
`

func (q *Queries) AppendNoteFieldSlot(ctx context.Context, noteTypeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, appendNoteFieldSlot, noteTypeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (note_id, template_id, ordinal, deck_id) VALUES ($1, $2, $3, $4) RETURNING id, note_id, template_id, ordinal, deck_id, anki_id
`

type CreateCardParams struct {
	NoteID     pgtype.UUID
	TemplateID pgtype.UUID
	Ordinal    int32
	DeckID     pgtype.UUID
}

// Called once per card in the create set (§0.3's "create" batch is small -- at most one row
// per template/cloze ordinal) rather than as a single multi-row statement: sqlc's query
// analyzer cannot resolve a two-array unnest(...) without a live database catalog.
func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.NoteID,
		arg.TemplateID,
		arg.Ordinal,
		arg.DeckID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.TemplateID,
		&i.Ordinal,
		&i.DeckID,
		&i.AnkiID,
	)
	return i, err
}

const createCardsForNewTemplate = `-- name: CreateCardsForNewTemplate :execrows
INSERT INTO cards (note_id, template_id, ordinal, deck_id)
SELECT n.id, $1, $2, n.deck_id
FROM notes n WHERE n.note_type_id = $3
ON CONFLICT (note_id, ordinal) DO NOTHING
`

type CreateCardsForNewTemplateParams struct {
	TemplateID pgtype.UUID
	Ordinal    int32
	NoteTypeID pgtype.UUID
}

// One card per existing note when a template is appended to a non-cloze note type (#54 §0.5).
// Filed in each note's home deck: notes.deck_id is the default for cards generated later
// (architecture.md §20).
func (q *Queries) CreateCardsForNewTemplate(ctx context.Context, arg CreateCardsForNewTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, createCardsForNewTemplate, arg.TemplateID, arg.Ordinal, arg.NoteTypeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCardsByOrdinals = `-- name: DeleteCardsByOrdinals :execrows
DELETE FROM cards WHERE note_id = $1 AND ordinal = ANY($2::int[])
`

type DeleteCardsByOrdinalsParams struct {
	NoteID   pgtype.UUID
	Ordinals []int32
}

func (q *Queries) DeleteCardsByOrdinals(ctx context.Context, arg DeleteCardsByOrdinalsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCardsByOrdinals, arg.NoteID, arg.Ordinals)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCardsForNote = `-- name: ListCardsForNote :many
SELECT ordinal FROM cards WHERE note_id = $1 ORDER BY ordinal
`

// Non-locking read for a preview (no FOR UPDATE): used only to compute which ordinals a note-type
// change would add/remove, before the user has confirmed anything. The actual mutation re-reads
// via ListCardsForNoteForUpdate inside SyncNoteCards's transaction, so a stale preview here is
// never a correctness problem -- worst case the confirmation copy is one save behind.
func (q *Queries) ListCardsForNote(ctx context.Context, noteID pgtype.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, listCardsForNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var ordinal int32
		if err := rows.Scan(&ordinal); err != nil {
			return nil, err
		}
		items = append(items, ordinal)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsForNoteForUpdate = `-- name: ListCardsForNoteForUpdate :many

SELECT id, ordinal, template_id, deck_id FROM cards WHERE note_id = $1 ORDER BY ordinal FOR UPDATE
`

type ListCardsForNoteForUpdateRow struct {
	ID         pgtype.UUID
	Ordinal    int32
	TemplateID pgtype.UUID
	DeckID     pgtype.UUID
}

// Cards are content addressing only -- no scheduling columns exist here to lose (CLAUDE.md §2.1).
// These four statements are the whole of card regeneration; see internal/db/cards.go for the
// diff that calls them and docs/schema.md's card-regeneration trap for why it is a diff.
func (q *Queries) ListCardsForNoteForUpdate(ctx context.Context, noteID pgtype.UUID) ([]ListCardsForNoteForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listCardsForNoteForUpdate, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsForNoteForUpdateRow
	for rows.Next() {
		var i ListCardsForNoteForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.Ordinal,
			&i.TemplateID,
			&i.DeckID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardTemplate = `-- name: UpdateCardTemplate :execrows
UPDATE cards SET template_id = $1 WHERE id = $2
`

type UpdateCardTemplateParams struct {
	TemplateID pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) UpdateCardTemplate(ctx context.Context, arg UpdateCardTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardTemplate, arg.TemplateID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
