// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCardsForTemplates = `-- name: CountCardsForTemplates :one
SELECT count(*) FROM cards WHERE template_id = ANY($1::uuid[])
`

// internal/http/notetypes.go's #89 structural-change confirmation preview.
func (q *Queries) CountCardsForTemplates(ctx context.Context, templateIds []pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCardsForTemplates, templateIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (note_id, template_id, ordinal, deck_id) VALUES ($1, $2, $3, $4) RETURNING id, note_id, template_id, ordinal, deck_id, anki_id, import_due_position
`

type CreateCardParams struct {
	NoteID     pgtype.UUID
	TemplateID pgtype.UUID
	Ordinal    int32
	DeckID     pgtype.UUID
}

// Called once per card in the create set (§0.3's "create" batch is small -- at most one row
// per template/cloze ordinal) rather than as a single multi-row statement: sqlc's query
// analyzer cannot resolve a two-array unnest(...) without a live database catalog.
func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.NoteID,
		arg.TemplateID,
		arg.Ordinal,
		arg.DeckID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.TemplateID,
		&i.Ordinal,
		&i.DeckID,
		&i.AnkiID,
		&i.ImportDuePosition,
	)
	return i, err
}

const createCardsForNewTemplate = `-- name: CreateCardsForNewTemplate :execrows
INSERT INTO cards (note_id, template_id, ordinal, deck_id)
SELECT n.id, $1, $2, n.deck_id
FROM notes n WHERE n.note_type_id = $3
ON CONFLICT (note_id, ordinal) DO NOTHING
`

type CreateCardsForNewTemplateParams struct {
	TemplateID pgtype.UUID
	Ordinal    int32
	NoteTypeID pgtype.UUID
}

// One card per existing note when a template is appended to a non-cloze note type (#54 §0.5).
// Filed in each note's home deck: notes.deck_id is the default for cards generated later
// (architecture.md §20).
func (q *Queries) CreateCardsForNewTemplate(ctx context.Context, arg CreateCardsForNewTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, createCardsForNewTemplate, arg.TemplateID, arg.Ordinal, arg.NoteTypeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCardsByOrdinals = `-- name: DeleteCardsByOrdinals :execrows
DELETE FROM cards WHERE note_id = $1 AND ordinal = ANY($2::int[])
`

type DeleteCardsByOrdinalsParams struct {
	NoteID   pgtype.UUID
	Ordinals []int32
}

func (q *Queries) DeleteCardsByOrdinals(ctx context.Context, arg DeleteCardsByOrdinalsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCardsByOrdinals, arg.NoteID, arg.Ordinals)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCardsForTemplates = `-- name: DeleteCardsForTemplates :execrows
DELETE FROM cards WHERE template_id = ANY($1::uuid[])
`

// A removed template's cards, across every note of the note type, in one statement (#89). Cascades
// user_card_state; leaves any review_log rows in place, orphaned but intact -- card_id has no FK
// (docs/schema.md's Deletion policy), so this is the same, already-decided convention #138 already
// exercises for a single note's card removal, just applied note-type-wide.
func (q *Queries) DeleteCardsForTemplates(ctx context.Context, templateIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCardsForTemplates, templateIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeCardOrdinalsForTemplates = `-- name: FinalizeCardOrdinalsForTemplates :execrows
WITH m AS (
    SELECT t.template_id, o.new_ordinal
    FROM unnest($1::uuid[]) WITH ORDINALITY AS t(template_id, ord)
    JOIN unnest($2::int[]) WITH ORDINALITY AS o(new_ordinal, ord)
      ON t.ord = o.ord
)
UPDATE cards c SET ordinal = m.new_ordinal FROM m WHERE c.template_id = m.template_id
`

type FinalizeCardOrdinalsForTemplatesParams struct {
	TemplateIds []pgtype.UUID
	NewOrdinals []int32
}

// Sets the real final ordinal for cards staged by OffsetCardOrdinalsForTemplates. Safe as one
// statement because every affected card is currently negative (from the offset above) and every
// target is non-negative and, by construction of the caller's plan, unique per note -- so no row's
// new value can collide with another affected row's current (still-negative) value, or with an
// untouched card's (already-final, non-negative) value.
func (q *Queries) FinalizeCardOrdinalsForTemplates(ctx context.Context, arg FinalizeCardOrdinalsForTemplatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeCardOrdinalsForTemplates, arg.TemplateIds, arg.NewOrdinals)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCardsForNote = `-- name: ListCardsForNote :many
SELECT ordinal FROM cards WHERE note_id = $1 ORDER BY ordinal
`

// Non-locking read for a preview (no FOR UPDATE): used only to compute which ordinals a note-type
// change would add/remove, before the user has confirmed anything. The actual mutation re-reads
// via ListCardsForNoteForUpdate inside SyncNoteCards's transaction, so a stale preview here is
// never a correctness problem -- worst case the confirmation copy is one save behind.
func (q *Queries) ListCardsForNote(ctx context.Context, noteID pgtype.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, listCardsForNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var ordinal int32
		if err := rows.Scan(&ordinal); err != nil {
			return nil, err
		}
		items = append(items, ordinal)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsForNoteForUpdate = `-- name: ListCardsForNoteForUpdate :many

SELECT id, ordinal, template_id, deck_id FROM cards WHERE note_id = $1 ORDER BY ordinal FOR UPDATE
`

type ListCardsForNoteForUpdateRow struct {
	ID         pgtype.UUID
	Ordinal    int32
	TemplateID pgtype.UUID
	DeckID     pgtype.UUID
}

// Cards are content addressing only -- no scheduling columns exist here to lose (CLAUDE.md §2.1).
// These four statements are the whole of card regeneration; see internal/db/cards.go for the
// diff that calls them and docs/schema.md's card-regeneration trap for why it is a diff.
func (q *Queries) ListCardsForNoteForUpdate(ctx context.Context, noteID pgtype.UUID) ([]ListCardsForNoteForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listCardsForNoteForUpdate, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsForNoteForUpdateRow
	for rows.Next() {
		var i ListCardsForNoteForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.Ordinal,
			&i.TemplateID,
			&i.DeckID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offsetCardOrdinalsForTemplates = `-- name: OffsetCardOrdinalsForTemplates :execrows
UPDATE cards SET ordinal = -(ordinal + 1) WHERE template_id = ANY($1::uuid[])
`

// Offsets every card backed by these templates to a negative, per-note-unique ordinal so that a
// subsequent finalize (FinalizeCardOrdinalsForTemplates) can permute ordinals -- including cyclic,
// not just pairwise -- without transiently violating cards_note_id_ordinal_key. Negative values
// never collide with a real (>=0) ordinal, touched or not, and the transform x -> -(x+1) is
// injective, so cards that were already distinct per note stay distinct. Never committed in this
// shape -- FinalizeCardOrdinalsForTemplates always runs before the transaction commits.
func (q *Queries) OffsetCardOrdinalsForTemplates(ctx context.Context, templateIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, offsetCardOrdinalsForTemplates, templateIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCardTemplate = `-- name: UpdateCardTemplate :execrows
UPDATE cards SET template_id = $1 WHERE id = $2
`

type UpdateCardTemplateParams struct {
	TemplateID pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) UpdateCardTemplate(ctx context.Context, arg UpdateCardTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardTemplate, arg.TemplateID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
