// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCard = `-- name: GetCard :one
SELECT id, note_id, template_id, ordinal, deck_id, anki_id FROM cards WHERE id = $1
`

func (q *Queries) GetCard(ctx context.Context, id pgtype.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.TemplateID,
		&i.Ordinal,
		&i.DeckID,
		&i.AnkiID,
	)
	return i, err
}
