// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deck_access.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const grantFullDeckAccess = `-- name: GrantFullDeckAccess :exec
INSERT INTO deck_access (deck_id, user_id, can_view, can_study, can_edit_content,
                         can_edit_settings, can_manage_access, can_delete)
VALUES ($1, $2, true, true, true, true, true, true)
`

type GrantFullDeckAccessParams struct {
	DeckID pgtype.UUID
	UserID pgtype.UUID
}

// A deck's creator gets all six flags (docs/schema.md). A personal deck is the trivial case of
// this, not a separate code path.
func (q *Queries) GrantFullDeckAccess(ctx context.Context, arg GrantFullDeckAccessParams) error {
	_, err := q.db.Exec(ctx, grantFullDeckAccess, arg.DeckID, arg.UserID)
	return err
}
