// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeckContents = `-- name: CountDeckContents :one
SELECT (SELECT count(*) FROM notes n WHERE n.deck_id = $1) AS note_count,
       (SELECT count(*) FROM cards c WHERE c.deck_id = $1) AS card_count
FROM deck_access da
WHERE da.deck_id = $1 AND da.user_id = $2 AND da.can_view
`

type CountDeckContentsParams struct {
	DeckID pgtype.UUID
	UserID pgtype.UUID
}

type CountDeckContentsRow struct {
	NoteCount int64
	CardCount int64
}

func (q *Queries) CountDeckContents(ctx context.Context, arg CountDeckContentsParams) (CountDeckContentsRow, error) {
	row := q.db.QueryRow(ctx, countDeckContents, arg.DeckID, arg.UserID)
	var i CountDeckContentsRow
	err := row.Scan(&i.NoteCount, &i.CardCount)
	return i, err
}

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (owner_id, name, description) VALUES ($1, $2, $3) RETURNING id, owner_id, name, description, preset, created_at, modified_at, anki_id
`

type CreateDeckParams struct {
	OwnerID     pgtype.UUID
	Name        string
	Description string
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck, arg.OwnerID, arg.Name, arg.Description)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Preset,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}

const getDeckForContentEdit = `-- name: GetDeckForContentEdit :one
SELECT d.id, d.owner_id, d.name, d.description, d.preset, d.created_at, d.modified_at, d.anki_id
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $1
                   AND da.can_view AND da.can_edit_content
WHERE d.id = $2
`

type GetDeckForContentEditParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

func (q *Queries) GetDeckForContentEdit(ctx context.Context, arg GetDeckForContentEditParams) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckForContentEdit, arg.UserID, arg.DeckID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Preset,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}

const getDeckForSettingsEdit = `-- name: GetDeckForSettingsEdit :one
SELECT d.id, d.owner_id, d.name, d.description, d.preset, d.created_at, d.modified_at, d.anki_id, da.can_delete
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $1
                   AND da.can_view AND da.can_edit_settings
WHERE d.id = $2
`

type GetDeckForSettingsEditParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

type GetDeckForSettingsEditRow struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	Name        string
	Description string
	Preset      []byte
	CreatedAt   pgtype.Timestamptz
	ModifiedAt  pgtype.Timestamptz
	AnkiID      pgtype.Int8
	CanDelete   bool
}

func (q *Queries) GetDeckForSettingsEdit(ctx context.Context, arg GetDeckForSettingsEditParams) (GetDeckForSettingsEditRow, error) {
	row := q.db.QueryRow(ctx, getDeckForSettingsEdit, arg.UserID, arg.DeckID)
	var i GetDeckForSettingsEditRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Preset,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
		&i.CanDelete,
	)
	return i, err
}

const getDeckForUser = `-- name: GetDeckForUser :one
SELECT d.id, d.owner_id, d.name, d.description, d.preset, d.created_at, d.modified_at, d.anki_id, da.can_edit_content, da.can_edit_settings, da.can_manage_access
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $1 AND da.can_view
WHERE d.id = $2
`

type GetDeckForUserParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

type GetDeckForUserRow struct {
	ID              pgtype.UUID
	OwnerID         pgtype.UUID
	Name            string
	Description     string
	Preset          []byte
	CreatedAt       pgtype.Timestamptz
	ModifiedAt      pgtype.Timestamptz
	AnkiID          pgtype.Int8
	CanEditContent  bool
	CanEditSettings bool
	CanManageAccess bool
}

func (q *Queries) GetDeckForUser(ctx context.Context, arg GetDeckForUserParams) (GetDeckForUserRow, error) {
	row := q.db.QueryRow(ctx, getDeckForUser, arg.UserID, arg.DeckID)
	var i GetDeckForUserRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Preset,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
		&i.CanEditContent,
		&i.CanEditSettings,
		&i.CanManageAccess,
	)
	return i, err
}

const listDecksForUser = `-- name: ListDecksForUser :many
SELECT d.id, d.owner_id, d.name, d.description, d.preset, d.created_at, d.modified_at, d.anki_id, (SELECT count(*) FROM cards c WHERE c.deck_id = d.id) AS card_count, da.can_edit_settings, da.can_edit_content,
       (SELECT count(*) FROM deck_access da2 WHERE da2.deck_id = d.id) > 1 AS is_shared
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $1 AND da.can_view
ORDER BY d.name
`

type ListDecksForUserRow struct {
	ID              pgtype.UUID
	OwnerID         pgtype.UUID
	Name            string
	Description     string
	Preset          []byte
	CreatedAt       pgtype.Timestamptz
	ModifiedAt      pgtype.Timestamptz
	AnkiID          pgtype.Int8
	CardCount       int64
	CanEditSettings bool
	CanEditContent  bool
	IsShared        bool
}

// #190: is_shared drives the shared-vs-private icon on /decks/ -- a deck is shared once more
// than one user has a deck_access row on it (the owner's own row is auto-inserted on create).
func (q *Queries) ListDecksForUser(ctx context.Context, userID pgtype.UUID) ([]ListDecksForUserRow, error) {
	rows, err := q.db.Query(ctx, listDecksForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecksForUserRow
	for rows.Next() {
		var i ListDecksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Preset,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AnkiID,
			&i.CardCount,
			&i.CanEditSettings,
			&i.CanEditContent,
			&i.IsShared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyableDecksForUser = `-- name: ListStudyableDecksForUser :many
SELECT d.id, d.owner_id, d.name, d.description, d.preset, d.created_at, d.modified_at, d.anki_id
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $1
                   AND da.can_view AND da.can_study
ORDER BY d.name
`

// #169: the decks a mixed "Study All" session may draw from -- can_study, not just can_view (a
// deck can be shared read-only, which must not let it contribute cards).
func (q *Queries) ListStudyableDecksForUser(ctx context.Context, userID pgtype.UUID) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listStudyableDecksForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Preset,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AnkiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeck = `-- name: UpdateDeck :execrows
UPDATE decks d
SET name = $1,
    description = $2,
    -- #101/#115/#116/#118/#154: nested-merge, not jsonb_set. jsonb_set('{}', '{new,perDay}', …, true)
    -- is a no-op when the parent object is missing, which every deck's default '{}' preset is. NULL
    -- leaves the corresponding key untouched so a form that doesn't carry the field can't wipe
    -- the setting. 'new', 'rev', 'priority', and 'due' are independent top-level keys, all patched
    -- off the same original d.preset and merged with a single ||  -- Postgres rejects assigning the
    -- same target column (preset) twice in one SET clause, so this has to be one expression, not
    -- four. Within 'new'/'rev', perDay and order are independently-nullable sub-patches of the same
    -- key; 'priority' and 'due' have only the one field so far, so they skip that extra layer.
    -- priority is top-level rather than nested under 'new' (unlike its predecessor, new.mix) since
    -- it governs the whole day's new/due split (#118), not new-card mixing specifically.
    preset = (CASE WHEN $3::int IS NULL THEN d.preset
                   ELSE d.preset || jsonb_build_object('new',
                          COALESCE(d.preset -> 'new', '{}'::jsonb)
                          || jsonb_build_object('perDay', $3::int))
              END)
           || (CASE WHEN $4::int IS NULL AND $5::text IS NULL THEN '{}'::jsonb
                    ELSE jsonb_build_object('rev',
                           COALESCE(d.preset -> 'rev', '{}'::jsonb)
                           || (CASE WHEN $4::int IS NULL THEN '{}'::jsonb
                                    ELSE jsonb_build_object('perDay', $4::int) END)
                           || (CASE WHEN $5::text IS NULL THEN '{}'::jsonb
                                    ELSE jsonb_build_object('order', $5::text) END))
               END)
           || (CASE WHEN $6::text IS NULL THEN '{}'::jsonb
                    ELSE jsonb_build_object('priority', $6::text)
               END)
           || (CASE WHEN $7::int IS NULL THEN '{}'::jsonb
                    ELSE jsonb_build_object('due',
                           jsonb_build_object('lookAheadMinutes', $7::int))
               END),
    modified_at = now()
FROM deck_access da
WHERE d.id = $8 AND da.deck_id = d.id AND da.user_id = $9
  AND da.can_view AND da.can_edit_settings
`

type UpdateDeckParams struct {
	Name                string
	Description         string
	NewPerDay           pgtype.Int4
	RevPerDay           pgtype.Int4
	RevOrder            pgtype.Text
	Priority            pgtype.Text
	DueLookAheadMinutes pgtype.Int4
	DeckID              pgtype.UUID
	UserID              pgtype.UUID
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDeck,
		arg.Name,
		arg.Description,
		arg.NewPerDay,
		arg.RevPerDay,
		arg.RevOrder,
		arg.Priority,
		arg.DueLookAheadMinutes,
		arg.DeckID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
