// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeck = `-- name: GetDeck :one
SELECT id, owner_id, name, description, preset, created_at, modified_at, anki_id FROM decks WHERE id = $1
`

func (q *Queries) GetDeck(ctx context.Context, id pgtype.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeck, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Preset,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}
