// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deletion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeckAccessHolders = `-- name: CountDeckAccessHolders :one
SELECT
    count(*) FILTER (WHERE can_manage_access) AS manage_count,
    count(*) FILTER (WHERE can_delete)        AS delete_count
FROM deck_access
WHERE deck_id = $1
`

type CountDeckAccessHoldersRow struct {
	ManageCount int64
	DeleteCount int64
}

// The guard itself, run AFTER the mutation inside the same transaction. Zero of either count
// means the deck has been stranded and the caller must roll back.
func (q *Queries) CountDeckAccessHolders(ctx context.Context, deckID pgtype.UUID) (CountDeckAccessHoldersRow, error) {
	row := q.db.QueryRow(ctx, countDeckAccessHolders, deckID)
	var i CountDeckAccessHoldersRow
	err := row.Scan(&i.ManageCount, &i.DeleteCount)
	return i, err
}

const deleteDeckAccessRow = `-- name: DeleteDeckAccessRow :execrows
DELETE FROM deck_access WHERE deck_id = $1 AND user_id = $2
`

type DeleteDeckAccessRowParams struct {
	DeckID       pgtype.UUID
	TargetUserID pgtype.UUID
}

func (q *Queries) DeleteDeckAccessRow(ctx context.Context, arg DeleteDeckAccessRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeckAccessRow, arg.DeckID, arg.TargetUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeckRow = `-- name: DeleteDeckRow :execrows
DELETE FROM decks WHERE id = $1
`

// Step 4 of DeleteDeck. Cascades to cards (and through them to user_card_state), deck_access,
// per-deck user_fsrs_params, and media_refs. Authorisation happened under the lock above.
func (q *Queries) DeleteDeckRow(ctx context.Context, deckID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeckRow, deckID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotesOrphanedByDeckDelete = `-- name: DeleteNotesOrphanedByDeckDelete :execrows
DELETE FROM notes n
WHERE (
        n.deck_id = $1
        OR EXISTS (SELECT 1 FROM cards c WHERE c.note_id = n.id AND c.deck_id = $1)
      )
  AND NOT EXISTS (SELECT 1 FROM cards c WHERE c.note_id = n.id AND c.deck_id <> $1)
`

// Step 2 of DeleteDeck. Deletes every note that this deck delete would leave with no cards at
// all: notes homed here, and notes homed elsewhere whose cards all live here -- but only when
// nothing of theirs survives outside this deck. Cascades to cards and user_card_state.
// review_log is untouched and has no FK to cards (#51 §0.4).
func (q *Queries) DeleteNotesOrphanedByDeckDelete(ctx context.Context, deckID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotesOrphanedByDeckDelete, deckID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserCardStateForDeck = `-- name: DeleteUserCardStateForDeck :execrows
DELETE FROM user_card_state ucs
USING cards c
WHERE ucs.card_id = c.id AND c.deck_id = $1 AND ucs.user_id = $2
`

type DeleteUserCardStateForDeckParams struct {
	DeckID       pgtype.UUID
	TargetUserID pgtype.UUID
}

// Resets target_user_id's scheduling progress on one deck. review_log is untouched (#189,
// CLAUDE.md §2.5) -- the next review for a reset card starts fresh because gradeEvent treats a
// missing user_card_state row as FSRS's zero-value New state (internal/review/grade.go), not as
// a signal to replay history.
func (q *Queries) DeleteUserCardStateForDeck(ctx context.Context, arg DeleteUserCardStateForDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserCardStateForDeck, arg.DeckID, arg.TargetUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockDeckForAccessChange = `-- name: LockDeckForAccessChange :one
SELECT d.id
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $1
WHERE d.id = $2
  AND da.can_view AND da.can_manage_access
FOR UPDATE OF d
`

type LockDeckForAccessChangeParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

// Locks the deck and authorises an access change. Same 404-shaped no-row contract as
// LockDeckForDelete; the shared lock is what serialises concurrent revocations, without which
// two callers can each remove "the second-to-last" holder and strand the deck. can_view is
// required alongside can_manage_access to match GetDeckForAccessManage (deck_access.sql) --
// otherwise a can_manage_access-without-can_view caller would be 404'd on the access page and on
// grant but could still edit/revoke other collaborators' access via this path (#83 review).
func (q *Queries) LockDeckForAccessChange(ctx context.Context, arg LockDeckForAccessChangeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockDeckForAccessChange, arg.UserID, arg.DeckID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockDeckForDelete = `-- name: LockDeckForDelete :one

SELECT d.id
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $1
WHERE d.id = $2
  AND da.can_view
  AND da.can_delete
FOR UPDATE OF d
`

type LockDeckForDeleteParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

// Deck deletion and the deck_access last-holder guard. These are not standalone queries: each
// one is a step of a transaction orchestrated in internal/db/deletion.go, and running any of
// them alone is a bug. See docs/plans/51-deletion-policy.md §0.5 and §0.6.
// Locks the deck row for the duration of the transaction and authorises the caller in one step.
// No row means "absent OR invisible OR not permitted" -- deliberately indistinguishable, so a
// 403 can never become an existence oracle (docs/schema.md, Access control).
func (q *Queries) LockDeckForDelete(ctx context.Context, arg LockDeckForDeleteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockDeckForDelete, arg.UserID, arg.DeckID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const rehomeNotesOffDeck = `-- name: RehomeNotesOffDeck :execrows
UPDATE notes n
SET deck_id = (
        SELECT c.deck_id
        FROM cards c
        WHERE c.note_id = n.id AND c.deck_id <> $1
        ORDER BY c.ordinal, c.id
        LIMIT 1
    ),
    owner_id = (
        SELECT d.owner_id
        FROM cards c
        JOIN decks d ON d.id = c.deck_id
        WHERE c.note_id = n.id AND c.deck_id <> $1
        ORDER BY c.ordinal, c.id
        LIMIT 1
    ),
    modified_at = now()
WHERE n.deck_id = $1
`

// Step 3 of DeleteDeck. Every note still homed here provably has a surviving card elsewhere
// (the complement of the statement above), so the subquery cannot be NULL -- and if it ever were,
// the NOT NULL column rejects it loudly. Home deck = the deck of the lowest-ordinal surviving
// card, which is deterministic and matches architecture.md §20's definition of a home deck.
// owner_id is re-synced to the new home deck's owner in the same statement: docs/schema.md
// requires owner_id to track the current deck's owner (it's denormalised, not enforced by a DB
// constraint), and a re-home is exactly the kind of deck move that must not let it drift.
func (q *Queries) RehomeNotesOffDeck(ctx context.Context, deckID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, rehomeNotesOffDeck, deckID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDeckAccessRow = `-- name: UpdateDeckAccessRow :execrows
UPDATE deck_access
SET can_view          = $1,
    can_study         = $2,
    can_edit_content  = $3,
    can_edit_settings = $4,
    can_manage_access = $5,
    can_delete        = $6,
    can_view_progress = $7,
    can_view_flags    = $8
WHERE deck_id = $9 AND user_id = $10
`

type UpdateDeckAccessRowParams struct {
	CanView         bool
	CanStudy        bool
	CanEditContent  bool
	CanEditSettings bool
	CanManageAccess bool
	CanDelete       bool
	CanViewProgress bool
	CanViewFlags    bool
	DeckID          pgtype.UUID
	TargetUserID    pgtype.UUID
}

func (q *Queries) UpdateDeckAccessRow(ctx context.Context, arg UpdateDeckAccessRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDeckAccessRow,
		arg.CanView,
		arg.CanStudy,
		arg.CanEditContent,
		arg.CanEditSettings,
		arg.CanManageAccess,
		arg.CanDelete,
		arg.CanViewProgress,
		arg.CanViewFlags,
		arg.DeckID,
		arg.TargetUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
