// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCardsByOwner = `-- name: ListCardsByOwner :many
SELECT c.id, c.note_id, c.template_id, c.ordinal, c.deck_id, c.anki_id FROM cards c
JOIN notes n ON n.id = c.note_id
WHERE n.owner_id = $1
ORDER BY c.id
`

func (q *Queries) ListCardsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCardsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.TemplateID,
			&i.Ordinal,
			&i.DeckID,
			&i.AnkiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecksByOwner = `-- name: ListDecksByOwner :many

SELECT id, owner_id, name, description, preset, created_at, modified_at, anki_id FROM decks WHERE owner_id = $1 ORDER BY id
`

// Export (#59). Every statement here is called only from internal/apkg/dbexport.go, reading one
// owner's own content -- scoped directly by owner_id, the same convention import.sql uses,
// not deck_access: exporting is always the owner's own collection, never someone else's shared
// deck (architecture.md §7's Export section).
func (q *Queries) ListDecksByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listDecksByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Preset,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AnkiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldsForOwner = `-- name: ListFieldsForOwner :many
SELECT f.id, f.note_type_id, f.ordinal, f.name, f.font, f.size, f.is_rtl, f.sticky FROM fields f
JOIN note_types nt ON nt.id = f.note_type_id
WHERE nt.owner_id = $1
ORDER BY f.note_type_id, f.ordinal
`

func (q *Queries) ListFieldsForOwner(ctx context.Context, ownerID pgtype.UUID) ([]Field, error) {
	rows, err := q.db.Query(ctx, listFieldsForOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Field
	for rows.Next() {
		var i Field
		if err := rows.Scan(
			&i.ID,
			&i.NoteTypeID,
			&i.Ordinal,
			&i.Name,
			&i.Font,
			&i.Size,
			&i.IsRtl,
			&i.Sticky,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteTypesByOwner = `-- name: ListNoteTypesByOwner :many
SELECT id, owner_id, name, css, is_cloze, sort_field_idx, anki_id FROM note_types WHERE owner_id = $1 ORDER BY id
`

func (q *Queries) ListNoteTypesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]NoteType, error) {
	rows, err := q.db.Query(ctx, listNoteTypesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteType
	for rows.Next() {
		var i NoteType
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Css,
			&i.IsCloze,
			&i.SortFieldIdx,
			&i.AnkiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByOwner = `-- name: ListNotesByOwner :many
SELECT id, guid, owner_id, note_type_id, deck_id, fields, tags, checksum, created_at, modified_at, anki_id FROM notes WHERE owner_id = $1 ORDER BY id
`

func (q *Queries) ListNotesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.OwnerID,
			&i.NoteTypeID,
			&i.DeckID,
			&i.Fields,
			&i.Tags,
			&i.Checksum,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AnkiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewLogForOwnerExport = `-- name: ListReviewLogForOwnerExport :many
SELECT rl.id, rl.user_id, rl.card_id, rl.rating, rl.reviewed_at, rl.duration_ms, rl.state_before, rl.learning_steps_before, rl.stability_before, rl.difficulty_before, rl.elapsed_days_before, rl.scheduled_days_after, rl.fsrs_version, rl.review_kind, rl.anki_id FROM review_log rl
JOIN cards c ON c.id = rl.card_id
JOIN notes n ON n.id = c.note_id
WHERE n.owner_id = $1 AND rl.user_id = $1
ORDER BY rl.card_id, rl.reviewed_at
`

func (q *Queries) ListReviewLogForOwnerExport(ctx context.Context, ownerID pgtype.UUID) ([]ReviewLog, error) {
	rows, err := q.db.Query(ctx, listReviewLogForOwnerExport, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewLog
	for rows.Next() {
		var i ReviewLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.Rating,
			&i.ReviewedAt,
			&i.DurationMs,
			&i.StateBefore,
			&i.LearningStepsBefore,
			&i.StabilityBefore,
			&i.DifficultyBefore,
			&i.ElapsedDaysBefore,
			&i.ScheduledDaysAfter,
			&i.FsrsVersion,
			&i.ReviewKind,
			&i.AnkiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesForOwner = `-- name: ListTemplatesForOwner :many
SELECT t.id, t.note_type_id, t.ordinal, t.name, t.qfmt, t.afmt, t.browser_qfmt, t.browser_afmt FROM templates t
JOIN note_types nt ON nt.id = t.note_type_id
WHERE nt.owner_id = $1
ORDER BY t.note_type_id, t.ordinal
`

func (q *Queries) ListTemplatesForOwner(ctx context.Context, ownerID pgtype.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesForOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.NoteTypeID,
			&i.Ordinal,
			&i.Name,
			&i.Qfmt,
			&i.Afmt,
			&i.BrowserQfmt,
			&i.BrowserAfmt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCardStateForOwnerExport = `-- name: ListUserCardStateForOwnerExport :many
SELECT ucs.user_id, ucs.card_id, ucs.due, ucs.stability, ucs.difficulty, ucs.state, ucs.reps, ucs.lapses, ucs.elapsed_days, ucs.scheduled_days, ucs.learning_steps, ucs.last_review, ucs.suspended, ucs.buried_until, ucs.flag FROM user_card_state ucs
JOIN cards c ON c.id = ucs.card_id
JOIN notes n ON n.id = c.note_id
WHERE n.owner_id = $1 AND ucs.user_id = $1
`

// Only this user's OWN progress on their OWN cards -- a shared deck's other reviewers' state is
// exactly what apkg-format.md's Export section says cannot be represented in a single collection.
func (q *Queries) ListUserCardStateForOwnerExport(ctx context.Context, ownerID pgtype.UUID) ([]UserCardState, error) {
	rows, err := q.db.Query(ctx, listUserCardStateForOwnerExport, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCardState
	for rows.Next() {
		var i UserCardState
		if err := rows.Scan(
			&i.UserID,
			&i.CardID,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.State,
			&i.Reps,
			&i.Lapses,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.LearningSteps,
			&i.LastReview,
			&i.Suspended,
			&i.BuriedUntil,
			&i.Flag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
