// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fields.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createField = `-- name: CreateField :one
INSERT INTO fields (note_type_id, ordinal, name) VALUES ($1, $2, $3) RETURNING id, note_type_id, ordinal, name, font, size, is_rtl, sticky
`

type CreateFieldParams struct {
	NoteTypeID pgtype.UUID
	Ordinal    int32
	Name       string
}

func (q *Queries) CreateField(ctx context.Context, arg CreateFieldParams) (Field, error) {
	row := q.db.QueryRow(ctx, createField, arg.NoteTypeID, arg.Ordinal, arg.Name)
	var i Field
	err := row.Scan(
		&i.ID,
		&i.NoteTypeID,
		&i.Ordinal,
		&i.Name,
		&i.Font,
		&i.Size,
		&i.IsRtl,
		&i.Sticky,
	)
	return i, err
}

const deleteFieldsForNoteType = `-- name: DeleteFieldsForNoteType :execrows
DELETE FROM fields WHERE note_type_id = $1
`

func (q *Queries) DeleteFieldsForNoteType(ctx context.Context, noteTypeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFieldsForNoteType, noteTypeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFieldsForNoteType = `-- name: ListFieldsForNoteType :many
SELECT id, note_type_id, ordinal, name, font, size, is_rtl, sticky FROM fields WHERE note_type_id = $1 ORDER BY ordinal
`

func (q *Queries) ListFieldsForNoteType(ctx context.Context, noteTypeID pgtype.UUID) ([]Field, error) {
	rows, err := q.db.Query(ctx, listFieldsForNoteType, noteTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Field
	for rows.Next() {
		var i Field
		if err := rows.Scan(
			&i.ID,
			&i.NoteTypeID,
			&i.Ordinal,
			&i.Name,
			&i.Font,
			&i.Size,
			&i.IsRtl,
			&i.Sticky,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldsForNoteTypes = `-- name: ListFieldsForNoteTypes :many
SELECT note_type_id, ordinal, name FROM fields
WHERE note_type_id = ANY($1::uuid[])
ORDER BY note_type_id, ordinal
`

type ListFieldsForNoteTypesRow struct {
	NoteTypeID pgtype.UUID
	Ordinal    int32
	Name       string
}

func (q *Queries) ListFieldsForNoteTypes(ctx context.Context, noteTypeIds []pgtype.UUID) ([]ListFieldsForNoteTypesRow, error) {
	rows, err := q.db.Query(ctx, listFieldsForNoteTypes, noteTypeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFieldsForNoteTypesRow
	for rows.Next() {
		var i ListFieldsForNoteTypesRow
		if err := rows.Scan(&i.NoteTypeID, &i.Ordinal, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameField = `-- name: RenameField :execrows
UPDATE fields SET name = $1 WHERE id = $2 AND note_type_id = $3
`

type RenameFieldParams struct {
	Name       string
	ID         pgtype.UUID
	NoteTypeID pgtype.UUID
}

func (q *Queries) RenameField(ctx context.Context, arg RenameFieldParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameField, arg.Name, arg.ID, arg.NoteTypeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
