// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenFlagsForDeck = `-- name: CountOpenFlagsForDeck :one
SELECT count(*) FROM card_flags WHERE deck_id = $1 AND status = 'open'
`

// Feeds the deck page's nav badge (deck.html), the same idea as CountOtherProgressViewers.
func (q *Queries) CountOpenFlagsForDeck(ctx context.Context, deckID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenFlagsForDeck, deckID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCardForFlag = `-- name: GetCardForFlag :one
SELECT c.id, c.deck_id
FROM cards c
JOIN deck_access da ON da.deck_id = c.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_study
WHERE c.id = $2 AND c.deck_id = $3
`

type GetCardForFlagParams struct {
	UserID pgtype.UUID
	CardID pgtype.UUID
	DeckID pgtype.UUID
}

type GetCardForFlagRow struct {
	ID     pgtype.UUID
	DeckID pgtype.UUID
}

// Authorise-and-fetch for the create route: confirms card_id actually belongs to deck_id and the
// caller can study this deck. Returns just the ids UpsertCardFlag needs.
func (q *Queries) GetCardForFlag(ctx context.Context, arg GetCardForFlagParams) (GetCardForFlagRow, error) {
	row := q.db.QueryRow(ctx, getCardForFlag, arg.UserID, arg.CardID, arg.DeckID)
	var i GetCardForFlagRow
	err := row.Scan(&i.ID, &i.DeckID)
	return i, err
}

const getDeckForFlags = `-- name: GetDeckForFlags :one

SELECT d.id, d.owner_id, d.name, d.description, d.preset, d.created_at, d.modified_at, d.anki_id, da.can_edit_content
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $1
                   AND da.can_view AND da.can_view_flags
WHERE d.id = $2
`

type GetDeckForFlagsParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

type GetDeckForFlagsRow struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Name           string
	Description    string
	Preset         []byte
	CreatedAt      pgtype.Timestamptz
	ModifiedAt     pgtype.Timestamptz
	AnkiID         pgtype.Int8
	CanEditContent bool
}

// Card-comment feedback from students to the deck owner (#207, migration 00019). Mirrors
// progress.sql's authorise-and-fetch shape; can_view_flags is deck_access's eighth independent
// permission, deliberately separate from can_view_progress -- that flag is scoped to
// aggregate-only reads (#87), and a named student's comment is individual-level disclosure.
// can_edit_content is carried alongside so flags.html can decide whether a flagged card links to
// the note editor, same reason GetDeckForProgress (progress.sql) carries it.
func (q *Queries) GetDeckForFlags(ctx context.Context, arg GetDeckForFlagsParams) (GetDeckForFlagsRow, error) {
	row := q.db.QueryRow(ctx, getDeckForFlags, arg.UserID, arg.DeckID)
	var i GetDeckForFlagsRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Preset,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
		&i.CanEditContent,
	)
	return i, err
}

const listFlagsForDeck = `-- name: ListFlagsForDeck :many
SELECT cf.id, cf.comment, cf.status, cf.created_at, cf.resolved_at,
       u.email AS flagged_by_email, u.display_name AS flagged_by_display_name,
       n.id AS note_id, (n.fields ->> 0)::text AS label
FROM card_flags cf
JOIN users u ON u.id = cf.flagged_by_user_id
JOIN cards c ON c.id = cf.card_id
JOIN notes n ON n.id = c.note_id
JOIN deck_access da ON da.deck_id = cf.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_view_flags
WHERE cf.deck_id = $2 AND cf.status = $3
ORDER BY cf.created_at ASC
`

type ListFlagsForDeckParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
	Status string
}

type ListFlagsForDeckRow struct {
	ID                   pgtype.UUID
	Comment              string
	Status               string
	CreatedAt            pgtype.Timestamptz
	ResolvedAt           pgtype.Timestamptz
	FlaggedByEmail       string
	FlaggedByDisplayName string
	NoteID               pgtype.UUID
	Label                string
}

// Re-checks can_view_flags itself (CLAUDE.md §9: "every query touching a deck takes a user_id
// and joins deck_access... do not rely on handler-level guards alone") rather than trusting the
// handler's earlier GetDeckForFlags call -- self-defending the same way GrantDeckAccess/
// ResolveCardFlag embed their own authorisation. label mirrors ListLapseHotspotsForDeck's
// (progress.sql) card-label expression -- no rendered-HTML snapshot is stored, so this reads the
// note's *current* first field, which may already reflect a fix made since the student flagged it.
func (q *Queries) ListFlagsForDeck(ctx context.Context, arg ListFlagsForDeckParams) ([]ListFlagsForDeckRow, error) {
	rows, err := q.db.Query(ctx, listFlagsForDeck, arg.UserID, arg.DeckID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlagsForDeckRow
	for rows.Next() {
		var i ListFlagsForDeckRow
		if err := rows.Scan(
			&i.ID,
			&i.Comment,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.FlaggedByEmail,
			&i.FlaggedByDisplayName,
			&i.NoteID,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCardFlag = `-- name: ResolveCardFlag :execrows
UPDATE card_flags cf
SET status = 'resolved', resolved_at = now(), resolved_by_user_id = $1
FROM deck_access da
WHERE cf.id = $2 AND cf.deck_id = $3
  AND da.deck_id = cf.deck_id AND da.user_id = $1
  AND da.can_view AND da.can_view_flags
  AND cf.status = 'open'
`

type ResolveCardFlagParams struct {
	ResolvedByUserID pgtype.UUID
	FlagID           pgtype.UUID
	DeckID           pgtype.UUID
}

// Authorisation embedded in the join, same shape as GrantDeckAccess. deck_id is bound to the
// URL's {id} segment (not just derived from the flag), matching how every other URL-scoped
// mutate route (e.g. access.go's edit/delete) ties every id in the path together, so a flag
// from a different deck than the URL names 404s instead of silently resolving. Zero rows means
// the flag doesn't exist, belongs to another deck, is already resolved, or the caller lacks
// can_view_flags -- all collapsed to 404 by the handler (docs/schema.md).
func (q *Queries) ResolveCardFlag(ctx context.Context, arg ResolveCardFlagParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveCardFlag, arg.ResolvedByUserID, arg.FlagID, arg.DeckID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCardFlag = `-- name: UpsertCardFlag :exec
INSERT INTO card_flags (card_id, deck_id, flagged_by_user_id, comment)
VALUES ($1, $2, $3, $4)
ON CONFLICT (card_id, flagged_by_user_id) WHERE status = 'open'
DO UPDATE SET comment = EXCLUDED.comment, created_at = now()
`

type UpsertCardFlagParams struct {
	CardID          pgtype.UUID
	DeckID          pgtype.UUID
	FlaggedByUserID pgtype.UUID
	Comment         string
}

// Resubmitting while a flag is still open replaces the comment and bumps created_at, rather than
// piling up a second row -- enforced by card_flags_open_idx (migration 00019).
func (q *Queries) UpsertCardFlag(ctx context.Context, arg UpsertCardFlagParams) error {
	_, err := q.db.Exec(ctx, upsertCardFlag,
		arg.CardID,
		arg.DeckID,
		arg.FlaggedByUserID,
		arg.Comment,
	)
	return err
}
