// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImportedField = `-- name: CreateImportedField :one
INSERT INTO fields (note_type_id, ordinal, name, font, size, is_rtl, sticky)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, note_type_id, ordinal, name, font, size, is_rtl, sticky
`

type CreateImportedFieldParams struct {
	NoteTypeID pgtype.UUID `json:"note_type_id"`
	Ordinal    int32       `json:"ordinal"`
	Name       string      `json:"name"`
	Font       string      `json:"font"`
	Size       int32       `json:"size"`
	IsRtl      bool        `json:"is_rtl"`
	Sticky     bool        `json:"sticky"`
}

// The full field row: fields.sql's CreateField carries name only, which would silently drop an
// imported field's font/size/rtl/sticky.
func (q *Queries) CreateImportedField(ctx context.Context, arg CreateImportedFieldParams) (Field, error) {
	row := q.db.QueryRow(ctx, createImportedField,
		arg.NoteTypeID,
		arg.Ordinal,
		arg.Name,
		arg.Font,
		arg.Size,
		arg.IsRtl,
		arg.Sticky,
	)
	var i Field
	err := row.Scan(
		&i.ID,
		&i.NoteTypeID,
		&i.Ordinal,
		&i.Name,
		&i.Font,
		&i.Size,
		&i.IsRtl,
		&i.Sticky,
	)
	return i, err
}

const createImportedNote = `-- name: CreateImportedNote :one
INSERT INTO notes (guid, owner_id, note_type_id, deck_id, fields, tags, checksum,
                   created_at, modified_at, anki_id)
SELECT $1, d.owner_id, nt.id, d.id, $2, $3,
       $4, $5, $6, $7
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $8
                   AND da.can_view AND da.can_edit_content
JOIN note_types nt ON nt.id = $9 AND nt.owner_id = $8
WHERE d.id = $10
RETURNING id, guid, owner_id, note_type_id, deck_id, fields, tags, checksum, created_at, modified_at, anki_id
`

type CreateImportedNoteParams struct {
	Guid       string             `json:"guid"`
	Fields     []byte             `json:"fields"`
	Tags       []string           `json:"tags"`
	Checksum   int64              `json:"checksum"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	AnkiID     pgtype.Int8        `json:"anki_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	NoteTypeID pgtype.UUID        `json:"note_type_id"`
	DeckID     pgtype.UUID        `json:"deck_id"`
}

// Same deck_access authorisation as notes.sql's CreateNote, plus the imported columns. owner_id
// comes from the DECK, not the caller (migration 00015's composite FK rejects any other value).
func (q *Queries) CreateImportedNote(ctx context.Context, arg CreateImportedNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createImportedNote,
		arg.Guid,
		arg.Fields,
		arg.Tags,
		arg.Checksum,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.AnkiID,
		arg.UserID,
		arg.NoteTypeID,
		arg.DeckID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.OwnerID,
		&i.NoteTypeID,
		&i.DeckID,
		&i.Fields,
		&i.Tags,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}

const createImportedNoteType = `-- name: CreateImportedNoteType :one
INSERT INTO note_types (owner_id, name, css, is_cloze, sort_field_idx, anki_id)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, owner_id, name, css, is_cloze, sort_field_idx, anki_id
`

type CreateImportedNoteTypeParams struct {
	OwnerID      pgtype.UUID `json:"owner_id"`
	Name         string      `json:"name"`
	Css          string      `json:"css"`
	IsCloze      bool        `json:"is_cloze"`
	SortFieldIdx int32       `json:"sort_field_idx"`
	AnkiID       pgtype.Int8 `json:"anki_id"`
}

func (q *Queries) CreateImportedNoteType(ctx context.Context, arg CreateImportedNoteTypeParams) (NoteType, error) {
	row := q.db.QueryRow(ctx, createImportedNoteType,
		arg.OwnerID,
		arg.Name,
		arg.Css,
		arg.IsCloze,
		arg.SortFieldIdx,
		arg.AnkiID,
	)
	var i NoteType
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Css,
		&i.IsCloze,
		&i.SortFieldIdx,
		&i.AnkiID,
	)
	return i, err
}

const createImportedTemplate = `-- name: CreateImportedTemplate :one
INSERT INTO templates (note_type_id, ordinal, name, qfmt, afmt, browser_qfmt, browser_afmt)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, note_type_id, ordinal, name, qfmt, afmt, browser_qfmt, browser_afmt
`

type CreateImportedTemplateParams struct {
	NoteTypeID  pgtype.UUID `json:"note_type_id"`
	Ordinal     int32       `json:"ordinal"`
	Name        string      `json:"name"`
	Qfmt        string      `json:"qfmt"`
	Afmt        string      `json:"afmt"`
	BrowserQfmt string      `json:"browser_qfmt"`
	BrowserAfmt string      `json:"browser_afmt"`
}

// Same reason as CreateImportedField: templates.sql's CreateTemplate has no browser formats.
func (q *Queries) CreateImportedTemplate(ctx context.Context, arg CreateImportedTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createImportedTemplate,
		arg.NoteTypeID,
		arg.Ordinal,
		arg.Name,
		arg.Qfmt,
		arg.Afmt,
		arg.BrowserQfmt,
		arg.BrowserAfmt,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.NoteTypeID,
		&i.Ordinal,
		&i.Name,
		&i.Qfmt,
		&i.Afmt,
		&i.BrowserQfmt,
		&i.BrowserAfmt,
	)
	return i, err
}

const getDeckByOwnerAndName = `-- name: GetDeckByOwnerAndName :one

SELECT id, owner_id, name, description, preset, created_at, modified_at, anki_id FROM decks WHERE owner_id = $1 AND name = $2
`

type GetDeckByOwnerAndNameParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Name    string      `json:"name"`
}

// Import (#58). Every statement here is called only from internal/apkg/dbwrite.go, inside the
// one transaction an import runs in.
func (q *Queries) GetDeckByOwnerAndName(ctx context.Context, arg GetDeckByOwnerAndNameParams) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByOwnerAndName, arg.OwnerID, arg.Name)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Preset,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}

const getNoteByOwnerAndGuid = `-- name: GetNoteByOwnerAndGuid :one
SELECT id, guid, owner_id, note_type_id, deck_id, fields, tags, checksum, created_at, modified_at, anki_id FROM notes WHERE owner_id = $1 AND guid = $2
`

type GetNoteByOwnerAndGuidParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Guid    string      `json:"guid"`
}

func (q *Queries) GetNoteByOwnerAndGuid(ctx context.Context, arg GetNoteByOwnerAndGuidParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByOwnerAndGuid, arg.OwnerID, arg.Guid)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.OwnerID,
		&i.NoteTypeID,
		&i.DeckID,
		&i.Fields,
		&i.Tags,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}

const getNoteTypeByOwnerAndName = `-- name: GetNoteTypeByOwnerAndName :one
SELECT id, owner_id, name, css, is_cloze, sort_field_idx, anki_id FROM note_types WHERE owner_id = $1 AND name = $2
`

type GetNoteTypeByOwnerAndNameParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Name    string      `json:"name"`
}

func (q *Queries) GetNoteTypeByOwnerAndName(ctx context.Context, arg GetNoteTypeByOwnerAndNameParams) (NoteType, error) {
	row := q.db.QueryRow(ctx, getNoteTypeByOwnerAndName, arg.OwnerID, arg.Name)
	var i NoteType
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Css,
		&i.IsCloze,
		&i.SortFieldIdx,
		&i.AnkiID,
	)
	return i, err
}

const insertImportedReviewLog = `-- name: InsertImportedReviewLog :execrows
INSERT INTO review_log (
    user_id, card_id, rating, reviewed_at, duration_ms,
    state_before, learning_steps_before, elapsed_days_before, scheduled_days_after,
    review_kind, anki_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
)
ON CONFLICT (user_id, card_id, anki_id) DO NOTHING
`

type InsertImportedReviewLogParams struct {
	UserID              pgtype.UUID        `json:"user_id"`
	CardID              pgtype.UUID        `json:"card_id"`
	Rating              int16              `json:"rating"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	DurationMs          pgtype.Int4        `json:"duration_ms"`
	StateBefore         int16              `json:"state_before"`
	LearningStepsBefore int16              `json:"learning_steps_before"`
	ElapsedDaysBefore   int32              `json:"elapsed_days_before"`
	ScheduledDaysAfter  int32              `json:"scheduled_days_after"`
	ReviewKind          int16              `json:"review_kind"`
	AnkiID              pgtype.Int8        `json:"anki_id"`
}

// Imported history. id is omitted so the column DEFAULT uuidv7() supplies it -- an imported row
// has no client-generated id and this package must not grow a UUID dependency to invent one.
// stability_before / difficulty_before / fsrs_version stay NULL: Anki's revlog carries SM-2
// values, and writing a fabricated FSRS prior would be permanently wrong training data
// (CLAUDE.md §2.5). ON CONFLICT DO NOTHING makes a re-import a no-op on the dedup key.
func (q *Queries) InsertImportedReviewLog(ctx context.Context, arg InsertImportedReviewLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertImportedReviewLog,
		arg.UserID,
		arg.CardID,
		arg.Rating,
		arg.ReviewedAt,
		arg.DurationMs,
		arg.StateBefore,
		arg.LearningStepsBefore,
		arg.ElapsedDaysBefore,
		arg.ScheduledDaysAfter,
		arg.ReviewKind,
		arg.AnkiID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedImportedUserCardState = `-- name: SeedImportedUserCardState :execrows
INSERT INTO user_card_state (user_id, card_id, due, stability, difficulty, state, reps, lapses,
                             elapsed_days, scheduled_days, learning_steps, last_review,
                             suspended, flag)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11,
        $12, $13, $14)
ON CONFLICT (user_id, card_id) DO NOTHING
`

type SeedImportedUserCardStateParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	CardID        pgtype.UUID        `json:"card_id"`
	Due           pgtype.Timestamptz `json:"due"`
	Stability     float64            `json:"stability"`
	Difficulty    float64            `json:"difficulty"`
	State         int16              `json:"state"`
	Reps          int32              `json:"reps"`
	Lapses        int32              `json:"lapses"`
	ElapsedDays   int32              `json:"elapsed_days"`
	ScheduledDays int32              `json:"scheduled_days"`
	LearningSteps int16              `json:"learning_steps"`
	LastReview    pgtype.Timestamptz `json:"last_review"`
	Suspended     bool               `json:"suspended"`
	Flag          int16              `json:"flag"`
}

// The seed path for a card that arrives with scheduling state but no review history. DO NOTHING,
// not DO UPDATE: an existing row is this user's own live progress and an imported snapshot never
// outranks it.
func (q *Queries) SeedImportedUserCardState(ctx context.Context, arg SeedImportedUserCardStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, seedImportedUserCardState,
		arg.UserID,
		arg.CardID,
		arg.Due,
		arg.Stability,
		arg.Difficulty,
		arg.State,
		arg.Reps,
		arg.Lapses,
		arg.ElapsedDays,
		arg.ScheduledDays,
		arg.LearningSteps,
		arg.LastReview,
		arg.Suspended,
		arg.Flag,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDeckAnkiID = `-- name: SetDeckAnkiID :execrows
UPDATE decks SET anki_id = $1, modified_at = now()
WHERE id = $2 AND anki_id IS NULL
`

type SetDeckAnkiIDParams struct {
	AnkiID pgtype.Int8 `json:"anki_id"`
	DeckID pgtype.UUID `json:"deck_id"`
}

// Re-import reuses the owner's deck of that name (docs/schema.md). anki_id is export fidelity
// only and is never a key -- deck id 1 is "Default" everywhere.
func (q *Queries) SetDeckAnkiID(ctx context.Context, arg SetDeckAnkiIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDeckAnkiID, arg.AnkiID, arg.DeckID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateImportedNote = `-- name: UpdateImportedNote :execrows
UPDATE notes n
SET fields = $1, tags = $2, checksum = $3,
    note_type_id = $4, modified_at = $5,
    anki_id = $6
FROM deck_access da
WHERE n.id = $7 AND da.deck_id = n.deck_id AND da.user_id = $8
  AND da.can_view AND da.can_edit_content
`

type UpdateImportedNoteParams struct {
	Fields     []byte             `json:"fields"`
	Tags       []string           `json:"tags"`
	Checksum   int64              `json:"checksum"`
	NoteTypeID pgtype.UUID        `json:"note_type_id"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	AnkiID     pgtype.Int8        `json:"anki_id"`
	NoteID     pgtype.UUID        `json:"note_id"`
	UserID     pgtype.UUID        `json:"user_id"`
}

// Re-import updates rather than inserts (CLAUDE.md §2.2, apkg-format.md). deck_id is NOT
// touched: a re-import must not silently move a note the user has since filed elsewhere.
func (q *Queries) UpdateImportedNote(ctx context.Context, arg UpdateImportedNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateImportedNote,
		arg.Fields,
		arg.Tags,
		arg.Checksum,
		arg.NoteTypeID,
		arg.ModifiedAt,
		arg.AnkiID,
		arg.NoteID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertImportedCard = `-- name: UpsertImportedCard :one
INSERT INTO cards (note_id, template_id, ordinal, deck_id, anki_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (note_id, ordinal) DO UPDATE
SET deck_id = EXCLUDED.deck_id, template_id = EXCLUDED.template_id, anki_id = EXCLUDED.anki_id
RETURNING id, note_id, template_id, ordinal, deck_id, anki_id
`

type UpsertImportedCardParams struct {
	NoteID     pgtype.UUID `json:"note_id"`
	TemplateID pgtype.UUID `json:"template_id"`
	Ordinal    int32       `json:"ordinal"`
	DeckID     pgtype.UUID `json:"deck_id"`
	AnkiID     pgtype.Int8 `json:"anki_id"`
}

// cards.deck_id comes from the CARD's own home deck, never flattened to the note's deck
// (architecture.md §20). ON CONFLICT keeps the existing card id, and with it its
// user_card_state and review_log history (docs/schema.md's card-regeneration trap).
func (q *Queries) UpsertImportedCard(ctx context.Context, arg UpsertImportedCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, upsertImportedCard,
		arg.NoteID,
		arg.TemplateID,
		arg.Ordinal,
		arg.DeckID,
		arg.AnkiID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.TemplateID,
		&i.Ordinal,
		&i.DeckID,
		&i.AnkiID,
	)
	return i, err
}
