// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_refs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMediaRef = `-- name: GetMediaRef :one
SELECT deck_id, filename, sha256 FROM media_refs WHERE deck_id = $1 AND filename = $2
`

type GetMediaRefParams struct {
	DeckID   pgtype.UUID `json:"deck_id"`
	Filename string      `json:"filename"`
}

func (q *Queries) GetMediaRef(ctx context.Context, arg GetMediaRefParams) (MediaRef, error) {
	row := q.db.QueryRow(ctx, getMediaRef, arg.DeckID, arg.Filename)
	var i MediaRef
	err := row.Scan(&i.DeckID, &i.Filename, &i.Sha256)
	return i, err
}
