// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_blobs.sql

package db

import (
	"context"
)

const getMediaBlob = `-- name: GetMediaBlob :one
SELECT sha256, size_bytes, mime, created_at FROM media_blobs WHERE sha256 = $1
`

func (q *Queries) GetMediaBlob(ctx context.Context, sha256 string) (MediaBlob, error) {
	row := q.db.QueryRow(ctx, getMediaBlob, sha256)
	var i MediaBlob
	err := row.Scan(
		&i.Sha256,
		&i.SizeBytes,
		&i.Mime,
		&i.CreatedAt,
	)
	return i, err
}
