// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID                pgtype.UUID
	NoteID            pgtype.UUID
	TemplateID        pgtype.UUID
	Ordinal           int32
	DeckID            pgtype.UUID
	AnkiID            pgtype.Int8
	ImportDuePosition pgtype.Int4
}

type Deck struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	Name        string
	Description string
	Preset      []byte
	CreatedAt   pgtype.Timestamptz
	ModifiedAt  pgtype.Timestamptz
	AnkiID      pgtype.Int8
}

type DeckAccess struct {
	DeckID          pgtype.UUID
	UserID          pgtype.UUID
	CanView         bool
	CanStudy        bool
	CanEditContent  bool
	CanEditSettings bool
	CanManageAccess bool
	CanDelete       bool
	CreatedAt       pgtype.Timestamptz
	CanViewProgress bool
}

type Field struct {
	ID         pgtype.UUID
	NoteTypeID pgtype.UUID
	Ordinal    int32
	Name       string
	Font       string
	Size       int32
	IsRtl      bool
	Sticky     bool
}

type MediaBlob struct {
	Sha256    string
	SizeBytes int64
	Mime      string
	CreatedAt pgtype.Timestamptz
}

type MediaRef struct {
	DeckID   pgtype.UUID
	Filename string
	Sha256   string
}

type Note struct {
	ID         pgtype.UUID
	Guid       string
	OwnerID    pgtype.UUID
	NoteTypeID pgtype.UUID
	DeckID     pgtype.UUID
	Fields     []byte
	Tags       []string
	Checksum   int64
	CreatedAt  pgtype.Timestamptz
	ModifiedAt pgtype.Timestamptz
	AnkiID     pgtype.Int8
}

type NoteType struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Name         string
	Css          string
	IsCloze      bool
	SortFieldIdx int32
	AnkiID       pgtype.Int8
}

type ReviewLog struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	CardID              pgtype.UUID
	Rating              int16
	ReviewedAt          pgtype.Timestamptz
	DurationMs          pgtype.Int4
	StateBefore         int16
	LearningStepsBefore int16
	StabilityBefore     pgtype.Float8
	DifficultyBefore    pgtype.Float8
	ElapsedDaysBefore   int32
	ScheduledDaysAfter  int32
	FsrsVersion         pgtype.Int2
	ReviewKind          int16
	AnkiID              pgtype.Int8
}

type Session struct {
	ID        string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Template struct {
	ID          pgtype.UUID
	NoteTypeID  pgtype.UUID
	Ordinal     int32
	Name        string
	Qfmt        string
	Afmt        string
	BrowserQfmt string
	BrowserAfmt string
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	Timezone     string
	DayStartHour int16
	CreatedAt    pgtype.Timestamptz
	AvatarSha256 pgtype.Text
}

type UserCardState struct {
	UserID        pgtype.UUID
	CardID        pgtype.UUID
	Due           pgtype.Timestamptz
	Stability     float64
	Difficulty    float64
	State         int16
	Reps          int32
	Lapses        int32
	ElapsedDays   int32
	ScheduledDays int32
	LearningSteps int16
	LastReview    pgtype.Timestamptz
	Suspended     bool
	BuriedUntil   pgtype.Date
	Flag          int16
}

type UserFsrsParam struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	DeckID           pgtype.UUID
	FsrsVersion      int16
	Params           []byte
	DesiredRetention float64
	OptimisedAt      pgtype.Timestamptz
	ReviewCountAtFit pgtype.Int4
}
