// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID         pgtype.UUID `json:"id"`
	NoteID     pgtype.UUID `json:"note_id"`
	TemplateID pgtype.UUID `json:"template_id"`
	Ordinal    int32       `json:"ordinal"`
	DeckID     pgtype.UUID `json:"deck_id"`
	AnkiID     pgtype.Int8 `json:"anki_id"`
}

type Deck struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Preset      []byte             `json:"preset"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	AnkiID      pgtype.Int8        `json:"anki_id"`
}

type DeckAccess struct {
	DeckID          pgtype.UUID        `json:"deck_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CanView         bool               `json:"can_view"`
	CanStudy        bool               `json:"can_study"`
	CanEditContent  bool               `json:"can_edit_content"`
	CanEditSettings bool               `json:"can_edit_settings"`
	CanManageAccess bool               `json:"can_manage_access"`
	CanDelete       bool               `json:"can_delete"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Field struct {
	ID         pgtype.UUID `json:"id"`
	NoteTypeID pgtype.UUID `json:"note_type_id"`
	Ordinal    int32       `json:"ordinal"`
	Name       string      `json:"name"`
	Font       string      `json:"font"`
	Size       int32       `json:"size"`
	IsRtl      bool        `json:"is_rtl"`
	Sticky     bool        `json:"sticky"`
}

type MediaBlob struct {
	Sha256    string             `json:"sha256"`
	SizeBytes int64              `json:"size_bytes"`
	Mime      string             `json:"mime"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MediaRef struct {
	DeckID   pgtype.UUID `json:"deck_id"`
	Filename string      `json:"filename"`
	Sha256   string      `json:"sha256"`
}

type Note struct {
	ID         pgtype.UUID        `json:"id"`
	Guid       string             `json:"guid"`
	OwnerID    pgtype.UUID        `json:"owner_id"`
	NoteTypeID pgtype.UUID        `json:"note_type_id"`
	DeckID     pgtype.UUID        `json:"deck_id"`
	Fields     []byte             `json:"fields"`
	Tags       []string           `json:"tags"`
	Checksum   int64              `json:"checksum"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	AnkiID     pgtype.Int8        `json:"anki_id"`
}

type NoteType struct {
	ID           pgtype.UUID `json:"id"`
	OwnerID      pgtype.UUID `json:"owner_id"`
	Name         string      `json:"name"`
	Css          string      `json:"css"`
	IsCloze      bool        `json:"is_cloze"`
	SortFieldIdx int32       `json:"sort_field_idx"`
	AnkiID       pgtype.Int8 `json:"anki_id"`
}

type ReviewLog struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	CardID              pgtype.UUID        `json:"card_id"`
	Rating              int16              `json:"rating"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	DurationMs          pgtype.Int4        `json:"duration_ms"`
	StateBefore         int16              `json:"state_before"`
	LearningStepsBefore int16              `json:"learning_steps_before"`
	StabilityBefore     pgtype.Float8      `json:"stability_before"`
	DifficultyBefore    pgtype.Float8      `json:"difficulty_before"`
	ElapsedDaysBefore   int32              `json:"elapsed_days_before"`
	ScheduledDaysAfter  int32              `json:"scheduled_days_after"`
	FsrsVersion         pgtype.Int2        `json:"fsrs_version"`
	ReviewKind          int16              `json:"review_kind"`
	AnkiID              pgtype.Int8        `json:"anki_id"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Template struct {
	ID          pgtype.UUID `json:"id"`
	NoteTypeID  pgtype.UUID `json:"note_type_id"`
	Ordinal     int32       `json:"ordinal"`
	Name        string      `json:"name"`
	Qfmt        string      `json:"qfmt"`
	Afmt        string      `json:"afmt"`
	BrowserQfmt string      `json:"browser_qfmt"`
	BrowserAfmt string      `json:"browser_afmt"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	Timezone     string             `json:"timezone"`
	DayStartHour int16              `json:"day_start_hour"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserCardState struct {
	UserID        pgtype.UUID        `json:"user_id"`
	CardID        pgtype.UUID        `json:"card_id"`
	Due           pgtype.Timestamptz `json:"due"`
	Stability     float64            `json:"stability"`
	Difficulty    float64            `json:"difficulty"`
	State         int16              `json:"state"`
	Reps          int32              `json:"reps"`
	Lapses        int32              `json:"lapses"`
	ElapsedDays   int32              `json:"elapsed_days"`
	ScheduledDays int32              `json:"scheduled_days"`
	LearningSteps int16              `json:"learning_steps"`
	LastReview    pgtype.Timestamptz `json:"last_review"`
	Suspended     bool               `json:"suspended"`
	BuriedUntil   pgtype.Date        `json:"buried_until"`
	Flag          int16              `json:"flag"`
}

type UserFsrsParam struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeckID           pgtype.UUID        `json:"deck_id"`
	FsrsVersion      int16              `json:"fsrs_version"`
	Params           []byte             `json:"params"`
	DesiredRetention float64            `json:"desired_retention"`
	OptimisedAt      pgtype.Timestamptz `json:"optimised_at"`
	ReviewCountAtFit pgtype.Int4        `json:"review_count_at_fit"`
}
