// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateNoteChecksums = `-- name: BulkUpdateNoteChecksums :execrows
WITH v AS (
    SELECT i.note_id, c.checksum
    FROM unnest($1::uuid[]) WITH ORDINALITY AS i(note_id, ord)
    JOIN unnest($2::bigint[]) WITH ORDINALITY AS c(checksum, ord)
      ON i.ord = c.ord
)
UPDATE notes n SET checksum = v.checksum FROM v WHERE n.id = v.note_id
`

type BulkUpdateNoteChecksumsParams struct {
	NoteIds   []pgtype.UUID
	Checksums []int64
}

func (q *Queries) BulkUpdateNoteChecksums(ctx context.Context, arg BulkUpdateNoteChecksumsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpdateNoteChecksums, arg.NoteIds, arg.Checksums)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (guid, owner_id, note_type_id, deck_id, fields, tags, checksum)
SELECT $1, d.owner_id, nt.id, d.id, $2, $3, $4
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $5
                   AND da.can_view AND da.can_edit_content
JOIN note_types nt ON nt.id = $6 AND nt.owner_id = $5
WHERE d.id = $7
RETURNING id, guid, owner_id, note_type_id, deck_id, fields, tags, checksum, created_at, modified_at, anki_id
`

type CreateNoteParams struct {
	Guid       string
	Fields     []byte
	Tags       []string
	Checksum   int64
	UserID     pgtype.UUID
	NoteTypeID pgtype.UUID
	DeckID     pgtype.UUID
}

// Owner_id comes from the DECK, not the caller: notes.owner_id is denormalised from
// decks.owner_id and, as of migration 00015, a composite FK rejects any other value.
func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.Guid,
		arg.Fields,
		arg.Tags,
		arg.Checksum,
		arg.UserID,
		arg.NoteTypeID,
		arg.DeckID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.OwnerID,
		&i.NoteTypeID,
		&i.DeckID,
		&i.Fields,
		&i.Tags,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes n
USING deck_access da
WHERE n.id = $1 AND da.deck_id = n.deck_id AND da.user_id = $2
  AND da.can_view AND da.can_edit_content
`

type DeleteNoteParams struct {
	NoteID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.NoteID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNoteForContentEdit = `-- name: GetNoteForContentEdit :one
SELECT n.id, n.guid, n.owner_id, n.note_type_id, n.deck_id, n.fields, n.tags, n.checksum, n.created_at, n.modified_at, n.anki_id, da.can_manage_access
FROM notes n
JOIN deck_access da ON da.deck_id = n.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_edit_content
WHERE n.id = $2
`

type GetNoteForContentEditParams struct {
	UserID pgtype.UUID
	NoteID pgtype.UUID
}

type GetNoteForContentEditRow struct {
	ID              pgtype.UUID
	Guid            string
	OwnerID         pgtype.UUID
	NoteTypeID      pgtype.UUID
	DeckID          pgtype.UUID
	Fields          []byte
	Tags            []string
	Checksum        int64
	CreatedAt       pgtype.Timestamptz
	ModifiedAt      pgtype.Timestamptz
	AnkiID          pgtype.Int8
	CanManageAccess bool
}

func (q *Queries) GetNoteForContentEdit(ctx context.Context, arg GetNoteForContentEditParams) (GetNoteForContentEditRow, error) {
	row := q.db.QueryRow(ctx, getNoteForContentEdit, arg.UserID, arg.NoteID)
	var i GetNoteForContentEditRow
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.OwnerID,
		&i.NoteTypeID,
		&i.DeckID,
		&i.Fields,
		&i.Tags,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
		&i.CanManageAccess,
	)
	return i, err
}

const getNoteForNoteTypeChange = `-- name: GetNoteForNoteTypeChange :one
SELECT n.id, n.guid, n.owner_id, n.note_type_id, n.deck_id, n.fields, n.tags, n.checksum, n.created_at, n.modified_at, n.anki_id
FROM notes n
JOIN deck_access da ON da.deck_id = n.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_edit_content AND da.can_manage_access
WHERE n.id = $2
`

type GetNoteForNoteTypeChangeParams struct {
	UserID pgtype.UUID
	NoteID pgtype.UUID
}

// Authorises the stronger can_manage_access permission required specifically for a note-type
// change (#138) -- ordinary content edits use can_edit_content alone via
// GetNoteForContentEdit/LockNoteForContentEdit. Same no-row-means-404 contract as those.
func (q *Queries) GetNoteForNoteTypeChange(ctx context.Context, arg GetNoteForNoteTypeChangeParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteForNoteTypeChange, arg.UserID, arg.NoteID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.OwnerID,
		&i.NoteTypeID,
		&i.DeckID,
		&i.Fields,
		&i.Tags,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}

const listNoteFieldsForNoteType = `-- name: ListNoteFieldsForNoteType :many
SELECT id, fields FROM notes WHERE note_type_id = $1
`

type ListNoteFieldsForNoteTypeRow struct {
	ID     pgtype.UUID
	Fields []byte
}

// Non-locking read used only to recompute checksum after a field remap that changes which field is
// now first (notes.checksum is sha1-of-stripped-html of field 0 -- see db.ComputeNoteChecksum).
func (q *Queries) ListNoteFieldsForNoteType(ctx context.Context, noteTypeID pgtype.UUID) ([]ListNoteFieldsForNoteTypeRow, error) {
	rows, err := q.db.Query(ctx, listNoteFieldsForNoteType, noteTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNoteFieldsForNoteTypeRow
	for rows.Next() {
		var i ListNoteFieldsForNoteTypeRow
		if err := rows.Scan(&i.ID, &i.Fields); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteIDsOfNoteType = `-- name: ListNoteIDsOfNoteType :many
SELECT id FROM notes WHERE note_type_id = $1
`

func (q *Queries) ListNoteIDsOfNoteType(ctx context.Context, noteTypeID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listNoteIDsOfNoteType, noteTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesInDeck = `-- name: ListNotesInDeck :many
SELECT n.id, n.fields ->> nt.sort_field_idx AS sort_text, n.tags, n.modified_at, nt.name AS note_type_name,
       (SELECT count(*) FROM cards c WHERE c.note_id = n.id) AS card_count
FROM notes n
JOIN note_types nt ON nt.id = n.note_type_id
JOIN deck_access da ON da.deck_id = n.deck_id AND da.user_id = $1 AND da.can_view
WHERE n.deck_id = $2
ORDER BY n.modified_at DESC
LIMIT 200
`

type ListNotesInDeckParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

type ListNotesInDeckRow struct {
	ID           pgtype.UUID
	SortText     interface{}
	Tags         []string
	ModifiedAt   pgtype.Timestamptz
	NoteTypeName string
	CardCount    int64
}

func (q *Queries) ListNotesInDeck(ctx context.Context, arg ListNotesInDeckParams) ([]ListNotesInDeckRow, error) {
	rows, err := q.db.Query(ctx, listNotesInDeck, arg.UserID, arg.DeckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesInDeckRow
	for rows.Next() {
		var i ListNotesInDeckRow
		if err := rows.Scan(
			&i.ID,
			&i.SortText,
			&i.Tags,
			&i.ModifiedAt,
			&i.NoteTypeName,
			&i.CardCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNoteForContentEdit = `-- name: LockNoteForContentEdit :one
SELECT n.id, n.guid, n.owner_id, n.note_type_id, n.deck_id, n.fields, n.tags, n.checksum, n.created_at, n.modified_at, n.anki_id
FROM notes n
JOIN deck_access da ON da.deck_id = n.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_edit_content
WHERE n.id = $2
FOR UPDATE OF n
`

type LockNoteForContentEditParams struct {
	UserID pgtype.UUID
	NoteID pgtype.UUID
}

// Locks the note for the duration of the transaction and authorises the caller in one step --
// the same no-row-means-404 contract as LockDeckForDelete. The lock is what makes the card
// ordinal diff in SyncNoteCards atomic against a concurrent edit of the same note.
func (q *Queries) LockNoteForContentEdit(ctx context.Context, arg LockNoteForContentEditParams) (Note, error) {
	row := q.db.QueryRow(ctx, lockNoteForContentEdit, arg.UserID, arg.NoteID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.OwnerID,
		&i.NoteTypeID,
		&i.DeckID,
		&i.Fields,
		&i.Tags,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}

const moveNoteCardsFromDeck = `-- name: MoveNoteCardsFromDeck :execrows
UPDATE cards SET deck_id = $1
WHERE note_id = $2 AND deck_id = $3
`

type MoveNoteCardsFromDeckParams struct {
	TargetDeckID pgtype.UUID
	NoteID       pgtype.UUID
	SourceDeckID pgtype.UUID
}

// Cards filed in the note's OLD home deck follow it; cards deliberately filed elsewhere stay
// put (architecture.md §20: a card belongs to exactly one deck, and a note's cards need not
// share one).
func (q *Queries) MoveNoteCardsFromDeck(ctx context.Context, arg MoveNoteCardsFromDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveNoteCardsFromDeck, arg.TargetDeckID, arg.NoteID, arg.SourceDeckID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveNoteToDeck = `-- name: MoveNoteToDeck :execrows
UPDATE notes n
SET deck_id = d.id, owner_id = d.owner_id, modified_at = now()
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $3
                   AND da.can_view AND da.can_edit_content
WHERE n.id = $1 AND d.id = $2
`

type MoveNoteToDeckParams struct {
	NoteID       pgtype.UUID
	TargetDeckID pgtype.UUID
	UserID       pgtype.UUID
}

// Moving a note must move owner_id with it (docs/schema.md, "must not drift"); migration 00015
// makes a drifted pair fail loudly instead of silently breaking the import key.
func (q *Queries) MoveNoteToDeck(ctx context.Context, arg MoveNoteToDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveNoteToDeck, arg.NoteID, arg.TargetDeckID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const remapNoteFields = `-- name: RemapNoteFields :execrows
UPDATE notes n
SET fields = (
    SELECT jsonb_agg(CASE WHEN t.old_ordinal < 0 THEN '""'::jsonb ELSE n.fields -> t.old_ordinal END
                     ORDER BY t.pos)
    FROM unnest($1::int[]) WITH ORDINALITY AS t(old_ordinal, pos)
),
    modified_at = now()
WHERE n.note_type_id = $2
`

type RemapNoteFieldsParams struct {
	OldOrdinals []int32
	NoteTypeID  pgtype.UUID
}

// Rewrites every note of note_type_id's fields array positionally, in one statement (#89): new
// position i takes its value from OLD ordinal old_ordinals[i], or an empty string when
// old_ordinals[i] is -1 (a field newly added by this same edit, which no note has ever held a
// value for -- same '""'::jsonb sentinel AppendNoteFieldSlot used). old_ordinals encodes the full
// old->new permutation and/or subset (a removed field simply has no entry) in one array, so this
// costs one UPDATE regardless of note count -- it scales in rows touched, not round trips.
func (q *Queries) RemapNoteFields(ctx context.Context, arg RemapNoteFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, remapNoteFields, arg.OldOrdinals, arg.NoteTypeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNoteContent = `-- name: UpdateNoteContent :execrows
UPDATE notes SET fields = $1, tags = $2,
                 checksum = $3, note_type_id = $4,
                 modified_at = now()
WHERE id = $5
`

type UpdateNoteContentParams struct {
	Fields     []byte
	Tags       []string
	Checksum   int64
	NoteTypeID pgtype.UUID
	NoteID     pgtype.UUID
}

// No deck_access join (CLAUDE.md §9): the caller (UpdateNoteWithCards) has already taken
// LockNoteForContentEdit on this note, which authorises can_view + can_edit_content and holds the
// row lock for the rest of the transaction.
func (q *Queries) UpdateNoteContent(ctx context.Context, arg UpdateNoteContentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNoteContent,
		arg.Fields,
		arg.Tags,
		arg.Checksum,
		arg.NoteTypeID,
		arg.NoteID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
