// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note_types.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNoteType = `-- name: GetNoteType :one
SELECT id, owner_id, name, css, is_cloze, sort_field_idx, anki_id FROM note_types WHERE id = $1
`

func (q *Queries) GetNoteType(ctx context.Context, id pgtype.UUID) (NoteType, error) {
	row := q.db.QueryRow(ctx, getNoteType, id)
	var i NoteType
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Css,
		&i.IsCloze,
		&i.SortFieldIdx,
		&i.AnkiID,
	)
	return i, err
}
