// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
DELETE FROM password_reset_tokens WHERE id = $1 AND expires_at > now() RETURNING user_id
`

// Single-use, atomically: the DELETE is the authorisation. Two concurrent submissions of the same
// link race on one row and exactly one gets RETURNING output; the other sees pgx.ErrNoRows.
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, id)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreatePasswordResetTokenParams struct {
	ID        string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :execrows
DELETE FROM password_reset_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePasswordResetTokensForUser = `-- name: DeletePasswordResetTokensForUser :execrows
DELETE FROM password_reset_tokens WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetTokensForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasswordResetTokensForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT user_id FROM password_reset_tokens WHERE id = $1 AND expires_at > now()
`

// Peek without consuming: backs GET /reset-password, which renders the form but must not spend
// the token (a prefetching browser or a link preview would otherwise burn it).
func (q *Queries) GetPasswordResetToken(ctx context.Context, id string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, id)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
