// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendNoteFieldSlot(ctx context.Context, noteTypeID pgtype.UUID) (int64, error)
	// The guard itself, run AFTER the mutation inside the same transaction. Zero of either count
	// means the deck has been stranded and the caller must roll back.
	CountDeckAccessHolders(ctx context.Context, deckID pgtype.UUID) (CountDeckAccessHoldersRow, error)
	CountDeckContents(ctx context.Context, arg CountDeckContentsParams) (CountDeckContentsRow, error)
	CountNotesOfNoteType(ctx context.Context, noteTypeID pgtype.UUID) (int64, error)
	// Queue summary (New/Learning/Due) for one deck's study page (#80). Same eligibility filters as
	// ListDueCardsForStudy -- suspended, buried, due-before-window-end, not already reviewed today --
	// so the counts agree with what /decks/{id}/review actually serves. Learning folds together
	// state 1 (learning) and 3 (relearning); Due is state 2 (review).
	CountQueueForDeck(ctx context.Context, arg CountQueueForDeckParams) (CountQueueForDeckRow, error)
	// Same queue summary, grouped by deck, for the /decks list (#80). One query for every deck the
	// user can view rather than one CountQueueForDeck call per row.
	CountQueueForUser(ctx context.Context, arg CountQueueForUserParams) ([]CountQueueForUserRow, error)
	// Called once per card in the create set (§0.3's "create" batch is small -- at most one row
	// per template/cloze ordinal) rather than as a single multi-row statement: sqlc's query
	// analyzer cannot resolve a two-array unnest(...) without a live database catalog.
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	// One card per existing note when a template is appended to a non-cloze note type (#54 §0.5).
	// Filed in each note's home deck: notes.deck_id is the default for cards generated later
	// (architecture.md §20).
	CreateCardsForNewTemplate(ctx context.Context, arg CreateCardsForNewTemplateParams) (int64, error)
	CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error)
	CreateField(ctx context.Context, arg CreateFieldParams) (Field, error)
	// The full field row: fields.sql's CreateField carries name only, which would silently drop an
	// imported field's font/size/rtl/sticky.
	CreateImportedField(ctx context.Context, arg CreateImportedFieldParams) (Field, error)
	// Same deck_access authorisation as notes.sql's CreateNote, plus the imported columns. owner_id
	// comes from the DECK, not the caller (migration 00015's composite FK rejects any other value).
	CreateImportedNote(ctx context.Context, arg CreateImportedNoteParams) (Note, error)
	CreateImportedNoteType(ctx context.Context, arg CreateImportedNoteTypeParams) (NoteType, error)
	// Same reason as CreateImportedField: templates.sql's CreateTemplate has no browser formats.
	CreateImportedTemplate(ctx context.Context, arg CreateImportedTemplateParams) (Template, error)
	// Dedup is by content, across ALL users (docs/schema.md, Media). ON CONFLICT DO NOTHING because a
	// blob row is immutable once written: size_bytes/mime are pure functions of the bytes the sha256
	// already commits to, so a second import of the same content has nothing new to write.
	CreateMediaBlob(ctx context.Context, arg CreateMediaBlobParams) error
	// First-seen-wins (docs/schema.md, Media): within one import collectMedia already resolves a
	// same-name collision before this is ever called; ON CONFLICT DO NOTHING extends the same policy
	// across re-imports -- the first ref a name ever got, on that deck, is the one kept.
	CreateMediaRef(ctx context.Context, arg CreateMediaRefParams) error
	// Owner_id comes from the DECK, not the caller: notes.owner_id is denormalised from
	// decks.owner_id and, as of migration 00015, a composite FK rejects any other value.
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateNoteType(ctx context.Context, arg CreateNoteTypeParams) (NoteType, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCardsByOrdinals(ctx context.Context, arg DeleteCardsByOrdinalsParams) (int64, error)
	DeleteDeckAccessRow(ctx context.Context, arg DeleteDeckAccessRowParams) (int64, error)
	// Step 4 of DeleteDeck. Cascades to cards (and through them to user_card_state), deck_access,
	// per-deck user_fsrs_params, and media_refs. Authorisation happened under the lock above.
	DeleteDeckRow(ctx context.Context, deckID pgtype.UUID) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteFieldsForNoteType(ctx context.Context, noteTypeID pgtype.UUID) (int64, error)
	DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error)
	// notes.note_type_id ON DELETE RESTRICT blocks this while any note exists (routes.md);
	// fields and templates cascade. The handler turns 23503 into 409.
	DeleteNoteType(ctx context.Context, arg DeleteNoteTypeParams) (int64, error)
	// Step 2 of DeleteDeck. Deletes every note that this deck delete would leave with no cards at
	// all: notes homed here, and notes homed elsewhere whose cards all live here -- but only when
	// nothing of theirs survives outside this deck. Cascades to cards and user_card_state.
	// review_log is untouched and has no FK to cards (#51 §0.4).
	DeleteNotesOrphanedByDeckDelete(ctx context.Context, deckID pgtype.UUID) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteTemplatesForNoteType(ctx context.Context, noteTypeID pgtype.UUID) (int64, error)
	EmailExists(ctx context.Context, email string) (bool, error)
	GetCard(ctx context.Context, id pgtype.UUID) (Card, error)
	GetDeck(ctx context.Context, id pgtype.UUID) (Deck, error)
	GetDeckAccess(ctx context.Context, arg GetDeckAccessParams) (DeckAccess, error)
	// Import (#58). Every statement here is called only from internal/apkg/dbwrite.go, inside the
	// one transaction an import runs in.
	GetDeckByOwnerAndName(ctx context.Context, arg GetDeckByOwnerAndNameParams) (Deck, error)
	GetDeckForContentEdit(ctx context.Context, arg GetDeckForContentEditParams) (Deck, error)
	GetDeckForSettingsEdit(ctx context.Context, arg GetDeckForSettingsEditParams) (Deck, error)
	GetDeckForStudy(ctx context.Context, arg GetDeckForStudyParams) (Deck, error)
	GetDeckForUser(ctx context.Context, arg GetDeckForUserParams) (Deck, error)
	GetDeckFsrsRetention(ctx context.Context, arg GetDeckFsrsRetentionParams) (float64, error)
	// The per-(user,deck) override if there is one, else the user's global row. deck_id NULLS LAST puts
	// the override first (CLAUDE.md §2.3, §2.4: never one parameter set across a cohort).
	GetEffectiveFsrsParams(ctx context.Context, arg GetEffectiveFsrsParamsParams) (GetEffectiveFsrsParamsRow, error)
	GetField(ctx context.Context, id pgtype.UUID) (Field, error)
	GetGlobalFsrsRetention(ctx context.Context, userID pgtype.UUID) (float64, error)
	GetMediaBlob(ctx context.Context, sha256 string) (MediaBlob, error)
	// Used by GET /media/{sha256} (routes.md): a blob is visible to a user only through a deck they
	// can_view that references it -- the same deck_access join every cross-user read goes through
	// (CLAUDE.md §9). Collapsing "blob doesn't exist" and "blob exists but caller can't see it" into
	// one pgx.ErrNoRows, like GetDeckForUser does, avoids confirming existence to a caller who can't.
	GetMediaBlobForUser(ctx context.Context, arg GetMediaBlobForUserParams) (MediaBlob, error)
	GetMediaRef(ctx context.Context, arg GetMediaRefParams) (MediaRef, error)
	GetNote(ctx context.Context, id pgtype.UUID) (Note, error)
	GetNoteByOwnerAndGuid(ctx context.Context, arg GetNoteByOwnerAndGuidParams) (Note, error)
	GetNoteForContentEdit(ctx context.Context, arg GetNoteForContentEditParams) (Note, error)
	GetNoteType(ctx context.Context, id pgtype.UUID) (NoteType, error)
	GetNoteTypeByOwnerAndName(ctx context.Context, arg GetNoteTypeByOwnerAndNameParams) (NoteType, error)
	GetNoteTypeForOwner(ctx context.Context, arg GetNoteTypeForOwnerParams) (NoteType, error)
	GetReviewLogEntry(ctx context.Context, id pgtype.UUID) (ReviewLog, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSessionUser(ctx context.Context, id string) (GetSessionUserRow, error)
	// The reviewer's queue (architecture.md §6). Every query here takes user_id and joins deck_access
	// (CLAUDE.md §9) -- review routes require can_view AND can_study.
	// The day boundary (docs/schema.md): a per-user rollover hour in the user's own timezone, not
	// midnight UTC. The arithmetic runs on the LOCAL wall clock, so a DST transition makes the study day
	// 23 or 25 hours long instead of silently shifting the rollover. `now` is a parameter, not now(), so
	// handler tests can pin the clock.
	GetStudyDayWindow(ctx context.Context, arg GetStudyDayWindowParams) (GetStudyDayWindowRow, error)
	GetTemplate(ctx context.Context, id pgtype.UUID) (Template, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserCardState(ctx context.Context, arg GetUserCardStateParams) (UserCardState, error)
	GetUserFsrsParams(ctx context.Context, id pgtype.UUID) (UserFsrsParam, error)
	// A deck's creator gets all six flags (docs/schema.md). A personal deck is the trivial case of
	// this, not a separate code path.
	GrantFullDeckAccess(ctx context.Context, arg GrantFullDeckAccessParams) error
	// Imported history. id is omitted so the column DEFAULT uuidv7() supplies it -- an imported row
	// has no client-generated id and this package must not grow a UUID dependency to invent one.
	// stability_before / difficulty_before / fsrs_version stay NULL: Anki's revlog carries SM-2
	// values, and writing a fabricated FSRS prior would be permanently wrong training data
	// (CLAUDE.md §2.5). ON CONFLICT DO NOTHING makes a re-import a no-op on the dedup key.
	InsertImportedReviewLog(ctx context.Context, arg InsertImportedReviewLogParams) (int64, error)
	// Every column except id is computed server-side (CLAUDE.md §2.7). anki_id stays NULL for rows this
	// reviewer writes. execrows, not exec: 0 rows means the id was already taken and this is a pure retry,
	// which must NOT be rescheduled from the row it already advanced.
	InsertReviewLog(ctx context.Context, arg InsertReviewLogParams) (int64, error)
	ListCardsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Card, error)
	// Cards are content addressing only -- no scheduling columns exist here to lose (CLAUDE.md §2.1).
	// These four statements are the whole of card regeneration; see internal/db/cards.go for the
	// diff that calls them and docs/schema.md's card-regeneration trap for why it is a diff.
	ListCardsForNoteForUpdate(ctx context.Context, noteID pgtype.UUID) ([]ListCardsForNoteForUpdateRow, error)
	// Export (#59). Every statement here is called only from internal/apkg/dbexport.go, reading one
	// owner's own content -- scoped directly by owner_id, the same convention import.sql uses,
	// not deck_access: exporting is always the owner's own collection, never someone else's shared
	// deck (architecture.md §7's Export section).
	ListDecksByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Deck, error)
	ListDecksForUser(ctx context.Context, userID pgtype.UUID) ([]ListDecksForUserRow, error)
	// The queue. Keyset over (COALESCE(due,'infinity'), card_id): due reviews first by due date, then
	// never-seen cards by id. 'infinity' (not NULL) keeps the sort key total -- a NULL inside the row
	// comparison below would silently drop every new card from every refill. Never-seen cards have no
	// user_card_state row at all, hence the LEFT JOIN and the COALESCEd columns.
	ListDueCardsForStudy(ctx context.Context, arg ListDueCardsForStudyParams) ([]ListDueCardsForStudyRow, error)
	// The idempotency check (architecture.md §6). Deliberately NOT scoped to user_id: review_log.id is a
	// global primary key, so an id taken by anyone is taken here -- scoping it would let ON CONFLICT drop
	// the row while the state write landed.
	ListExistingReviewLogIDs(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error)
	ListFieldsForNoteType(ctx context.Context, noteTypeID pgtype.UUID) ([]Field, error)
	ListFieldsForNoteTypes(ctx context.Context, noteTypeIds []pgtype.UUID) ([]ListFieldsForNoteTypesRow, error)
	ListFieldsForOwner(ctx context.Context, ownerID pgtype.UUID) ([]Field, error)
	ListNoteIDsOfNoteType(ctx context.Context, noteTypeID pgtype.UUID) ([]pgtype.UUID, error)
	// Note-type CSS for every card in the deck: sanitised once per page, never per card (#55's doc
	// comment), so a refilled card can never arrive before its styles.
	ListNoteTypeCSSForDeck(ctx context.Context, arg ListNoteTypeCSSForDeckParams) ([]ListNoteTypeCSSForDeckRow, error)
	ListNoteTypesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]NoteType, error)
	ListNoteTypesForOwner(ctx context.Context, ownerID pgtype.UUID) ([]ListNoteTypesForOwnerRow, error)
	ListNotesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Note, error)
	ListNotesInDeck(ctx context.Context, arg ListNotesInDeckParams) ([]ListNotesInDeckRow, error)
	// The replay path (architecture.md §6); backed by review_log_card_id_user_id_reviewed_at_idx. Only
	// rating and reviewed_at are read: a replay re-derives every *_before itself.
	ListReviewLogForCard(ctx context.Context, arg ListReviewLogForCardParams) ([]ListReviewLogForCardRow, error)
	ListReviewLogForOwnerExport(ctx context.Context, ownerID pgtype.UUID) ([]ReviewLog, error)
	// Per-card authorisation for a grade batch, which may span decks. A card missing from the result is
	// absent, invisible, or not studyable -- deliberately indistinguishable (docs/schema.md).
	ListStudyableCards(ctx context.Context, arg ListStudyableCardsParams) ([]ListStudyableCardsRow, error)
	ListTemplatesForNoteType(ctx context.Context, noteTypeID pgtype.UUID) ([]Template, error)
	ListTemplatesForOwner(ctx context.Context, ownerID pgtype.UUID) ([]Template, error)
	// Only this user's OWN progress on their OWN cards -- a shared deck's other reviewers' state is
	// exactly what apkg-format.md's Export section says cannot be represented in a single collection.
	ListUserCardStateForOwnerExport(ctx context.Context, ownerID pgtype.UUID) ([]UserCardState, error)
	// The per-(user,card) advisory lock, held to commit (architecture.md §6). Advisory rather than
	// SELECT ... FOR UPDATE because a never-seen card has no user_card_state row to lock, and two
	// concurrent first grades are exactly that case. The key is derived in Go -- see internal/review/
	// lock.go for the derivation and for why a batch's keys are acquired in ascending key order.
	LockCardForGrade(ctx context.Context, key int64) error
	// Locks the deck and authorises an access change. Same 404-shaped no-row contract as
	// LockDeckForDelete; the shared lock is what serialises concurrent revocations, without which
	// two callers can each remove "the second-to-last" holder and strand the deck.
	LockDeckForAccessChange(ctx context.Context, arg LockDeckForAccessChangeParams) (pgtype.UUID, error)
	// Deck deletion and the deck_access last-holder guard. These are not standalone queries: each
	// one is a step of a transaction orchestrated in internal/db/deletion.go, and running any of
	// them alone is a bug. See docs/plans/51-deletion-policy.md §0.5 and §0.6.
	// Locks the deck row for the duration of the transaction and authorises the caller in one step.
	// No row means "absent OR invisible OR not permitted" -- deliberately indistinguishable, so a
	// 403 can never become an existence oracle (docs/schema.md, Access control).
	LockDeckForDelete(ctx context.Context, arg LockDeckForDeleteParams) (pgtype.UUID, error)
	// Locks the note for the duration of the transaction and authorises the caller in one step --
	// the same no-row-means-404 contract as LockDeckForDelete. The lock is what makes the card
	// ordinal diff in SyncNoteCards atomic against a concurrent edit of the same note.
	LockNoteForContentEdit(ctx context.Context, arg LockNoteForContentEditParams) (Note, error)
	// Locks the note type row for the duration of an edit transaction, serialising it against a
	// concurrent edit of the same note type (docs/plans/54's TOCTOU note: the noteCount read below
	// and the structural field/template writes must not straddle a concurrent change).
	LockNoteTypeForOwner(ctx context.Context, arg LockNoteTypeForOwnerParams) (NoteType, error)
	// Cards filed in the note's OLD home deck follow it; cards deliberately filed elsewhere stay
	// put (architecture.md §20: a card belongs to exactly one deck, and a note's cards need not
	// share one).
	MoveNoteCardsFromDeck(ctx context.Context, arg MoveNoteCardsFromDeckParams) (int64, error)
	// Moving a note must move owner_id with it (docs/schema.md, "must not drift"); migration 00015
	// makes a drifted pair fail loudly instead of silently breaking the import key.
	MoveNoteToDeck(ctx context.Context, arg MoveNoteToDeckParams) (int64, error)
	// Step 3 of DeleteDeck. Every note still homed here provably has a surviving card elsewhere
	// (the complement of the statement above), so the subquery cannot be NULL -- and if it ever were,
	// the NOT NULL column rejects it loudly. Home deck = the deck of the lowest-ordinal surviving
	// card, which is deterministic and matches architecture.md §20's definition of a home deck.
	// owner_id is re-synced to the new home deck's owner in the same statement: docs/schema.md
	// requires owner_id to track the current deck's owner (it's denormalised, not enforced by a DB
	// constraint), and a re-home is exactly the kind of deck move that must not let it drift.
	RehomeNotesOffDeck(ctx context.Context, deckID pgtype.UUID) (int64, error)
	RenameField(ctx context.Context, arg RenameFieldParams) (int64, error)
	RenewSession(ctx context.Context, arg RenewSessionParams) error
	// The seed path for a card that arrives with scheduling state but no review history. DO NOTHING,
	// not DO UPDATE: an existing row is this user's own live progress and an imported snapshot never
	// outranks it.
	SeedImportedUserCardState(ctx context.Context, arg SeedImportedUserCardStateParams) (int64, error)
	// Re-import reuses the owner's deck of that name (docs/schema.md). anki_id is export fidelity
	// only and is never a key -- deck id 1 is "Default" everywhere.
	SetDeckAnkiID(ctx context.Context, arg SetDeckAnkiIDParams) (int64, error)
	UpdateDeck(ctx context.Context, arg UpdateDeckParams) (int64, error)
	UpdateDeckAccessRow(ctx context.Context, arg UpdateDeckAccessRowParams) (int64, error)
	// Re-import updates rather than inserts (CLAUDE.md §2.2, apkg-format.md). deck_id is NOT
	// touched: a re-import must not silently move a note the user has since filed elsewhere.
	UpdateImportedNote(ctx context.Context, arg UpdateImportedNoteParams) (int64, error)
	UpdateNoteContent(ctx context.Context, arg UpdateNoteContentParams) (int64, error)
	// is_cloze is immutable after creation: flipping it changes what every existing note's cards
	// mean. Not editable in the form, not settable here.
	UpdateNoteTypeRow(ctx context.Context, arg UpdateNoteTypeRowParams) (int64, error)
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	// Authorisation lives in the SELECT source, not a handler guard (CLAUDE.md §9): a caller
	// without can_view+can_study on the deck matches zero deck_access rows, so the INSERT touches
	// nothing and :execrows reports 0 -- the same "0 rows = not found" shape POST /decks/{id}/edit
	// uses (decks.sql UpdateDeck).
	UpsertDeckFsrsRetention(ctx context.Context, arg UpsertDeckFsrsRetentionParams) (int64, error)
	// Global row upsert targets the partial unique index (migration 00012:
	// user_fsrs_params_user_id_global_key) -- the plain (user_id, deck_id) index does not enforce
	// "one global row per user" because NULLs never conflict against each other in a btree unique
	// index, which is exactly why that second, partial index exists.
	UpsertGlobalFsrsRetention(ctx context.Context, arg UpsertGlobalFsrsRetentionParams) error
	// cards.deck_id comes from the CARD's own home deck, never flattened to the note's deck
	// (architecture.md §20). ON CONFLICT keeps the existing card id, and with it its
	// user_card_state and review_log history (docs/schema.md's card-regeneration trap).
	UpsertImportedCard(ctx context.Context, arg UpsertImportedCardParams) (Card, error)
	// The replay writer: unguarded, because a rebuild from review_log IS the newest truth for this card by
	// construction (architecture.md §6). Only internal/review.ReplayCard may call this.
	UpsertUserCardStateFromReplay(ctx context.Context, arg UpsertUserCardStateFromReplayParams) error
	// Last-write-wins by REVIEW time, not arrival time -- the property that makes a retrying sender safe
	// (architecture.md §6). suspended / buried_until / flag are user settings, not scheduling output, and
	// are never touched here.
	UpsertUserCardStateOnReview(ctx context.Context, arg UpsertUserCardStateOnReviewParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
