// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// The guard itself, run AFTER the mutation inside the same transaction. Zero of either count
	// means the deck has been stranded and the caller must roll back.
	CountDeckAccessHolders(ctx context.Context, deckID pgtype.UUID) (CountDeckAccessHoldersRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDeckAccessRow(ctx context.Context, arg DeleteDeckAccessRowParams) (int64, error)
	// Step 4 of DeleteDeck. Cascades to cards (and through them to user_card_state), deck_access,
	// per-deck user_fsrs_params, and media_refs. Authorisation happened under the lock above.
	DeleteDeckRow(ctx context.Context, deckID pgtype.UUID) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	// Step 2 of DeleteDeck. Deletes every note that this deck delete would leave with no cards at
	// all: notes homed here, and notes homed elsewhere whose cards all live here -- but only when
	// nothing of theirs survives outside this deck. Cascades to cards and user_card_state.
	// review_log is untouched and has no FK to cards (#51 §0.4).
	DeleteNotesOrphanedByDeckDelete(ctx context.Context, deckID pgtype.UUID) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	EmailExists(ctx context.Context, email string) (bool, error)
	GetCard(ctx context.Context, id pgtype.UUID) (Card, error)
	GetDeck(ctx context.Context, id pgtype.UUID) (Deck, error)
	GetDeckAccess(ctx context.Context, arg GetDeckAccessParams) (DeckAccess, error)
	GetField(ctx context.Context, id pgtype.UUID) (Field, error)
	GetMediaBlob(ctx context.Context, sha256 string) (MediaBlob, error)
	GetMediaRef(ctx context.Context, arg GetMediaRefParams) (MediaRef, error)
	GetNote(ctx context.Context, id pgtype.UUID) (Note, error)
	GetNoteType(ctx context.Context, id pgtype.UUID) (NoteType, error)
	GetReviewLogEntry(ctx context.Context, id pgtype.UUID) (ReviewLog, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSessionUser(ctx context.Context, id string) (GetSessionUserRow, error)
	GetTemplate(ctx context.Context, id pgtype.UUID) (Template, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserCardState(ctx context.Context, arg GetUserCardStateParams) (UserCardState, error)
	GetUserFsrsParams(ctx context.Context, id pgtype.UUID) (UserFsrsParam, error)
	// Locks the deck and authorises an access change. Same 404-shaped no-row contract as
	// LockDeckForDelete; the shared lock is what serialises concurrent revocations, without which
	// two callers can each remove "the second-to-last" holder and strand the deck.
	LockDeckForAccessChange(ctx context.Context, arg LockDeckForAccessChangeParams) (pgtype.UUID, error)
	// Deck deletion and the deck_access last-holder guard. These are not standalone queries: each
	// one is a step of a transaction orchestrated in internal/db/deletion.go, and running any of
	// them alone is a bug. See docs/plans/51-deletion-policy.md §0.5 and §0.6.
	// Locks the deck row for the duration of the transaction and authorises the caller in one step.
	// No row means "absent OR invisible OR not permitted" -- deliberately indistinguishable, so a
	// 403 can never become an existence oracle (docs/schema.md, Access control).
	LockDeckForDelete(ctx context.Context, arg LockDeckForDeleteParams) (pgtype.UUID, error)
	// Step 3 of DeleteDeck. Every note still homed here provably has a surviving card elsewhere
	// (the complement of the statement above), so the subquery cannot be NULL -- and if it ever were,
	// the NOT NULL column rejects it loudly. Home deck = the deck of the lowest-ordinal surviving
	// card, which is deterministic and matches architecture.md §20's definition of a home deck.
	// owner_id is re-synced to the new home deck's owner in the same statement: docs/schema.md
	// requires owner_id to track the current deck's owner (it's denormalised, not enforced by a DB
	// constraint), and a re-home is exactly the kind of deck move that must not let it drift.
	RehomeNotesOffDeck(ctx context.Context, deckID pgtype.UUID) (int64, error)
	RenewSession(ctx context.Context, arg RenewSessionParams) error
	UpdateDeckAccessRow(ctx context.Context, arg UpdateDeckAccessRowParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
