// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReviewLogEntry = `-- name: GetReviewLogEntry :one
SELECT id, user_id, card_id, rating, reviewed_at, duration_ms, state_before, learning_steps_before, stability_before, difficulty_before, elapsed_days_before, scheduled_days_after, fsrs_version, review_kind, anki_id FROM review_log WHERE id = $1
`

func (q *Queries) GetReviewLogEntry(ctx context.Context, id pgtype.UUID) (ReviewLog, error) {
	row := q.db.QueryRow(ctx, getReviewLogEntry, id)
	var i ReviewLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Rating,
		&i.ReviewedAt,
		&i.DurationMs,
		&i.StateBefore,
		&i.LearningStepsBefore,
		&i.StabilityBefore,
		&i.DifficultyBefore,
		&i.ElapsedDaysBefore,
		&i.ScheduledDaysAfter,
		&i.FsrsVersion,
		&i.ReviewKind,
		&i.AnkiID,
	)
	return i, err
}
