// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQueueForDeck = `-- name: CountQueueForDeck :one
SELECT count(*) FILTER (WHERE ucs.user_id IS NULL)   AS new_count,
       count(*) FILTER (WHERE ucs.state IN (1, 3))   AS learning_count,
       count(*) FILTER (WHERE ucs.state = 2)         AS due_count
FROM cards c
JOIN deck_access da ON da.deck_id = c.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_study
LEFT JOIN user_card_state ucs ON ucs.user_id = $1 AND ucs.card_id = c.id
WHERE c.deck_id = $2
  AND NOT COALESCE(ucs.suspended, false)
  AND (ucs.buried_until IS NULL OR ucs.buried_until <= ($3::timestamptz)::date)
  AND (ucs.due IS NULL OR ucs.due < $4::timestamptz)
  AND (ucs.last_review IS NULL OR ucs.last_review < $3::timestamptz)
`

type CountQueueForDeckParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	DeckID        pgtype.UUID        `json:"deck_id"`
	StudyDayStart pgtype.Timestamptz `json:"study_day_start"`
	StudyDayEnd   pgtype.Timestamptz `json:"study_day_end"`
}

type CountQueueForDeckRow struct {
	NewCount      int64 `json:"new_count"`
	LearningCount int64 `json:"learning_count"`
	DueCount      int64 `json:"due_count"`
}

// Queue summary (New/Learning/Due) for one deck's study page (#80). Same eligibility filters as
// ListDueCardsForStudy -- suspended, buried, due-before-window-end, not already reviewed today --
// so the counts agree with what /decks/{id}/review actually serves. Learning folds together
// state 1 (learning) and 3 (relearning); Due is state 2 (review).
func (q *Queries) CountQueueForDeck(ctx context.Context, arg CountQueueForDeckParams) (CountQueueForDeckRow, error) {
	row := q.db.QueryRow(ctx, countQueueForDeck,
		arg.UserID,
		arg.DeckID,
		arg.StudyDayStart,
		arg.StudyDayEnd,
	)
	var i CountQueueForDeckRow
	err := row.Scan(&i.NewCount, &i.LearningCount, &i.DueCount)
	return i, err
}

const countQueueForUser = `-- name: CountQueueForUser :many
SELECT c.deck_id                                     AS deck_id,
       count(*) FILTER (WHERE ucs.user_id IS NULL)   AS new_count,
       count(*) FILTER (WHERE ucs.state IN (1, 3))   AS learning_count,
       count(*) FILTER (WHERE ucs.state = 2)         AS due_count
FROM cards c
JOIN deck_access da ON da.deck_id = c.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_study
LEFT JOIN user_card_state ucs ON ucs.user_id = $1 AND ucs.card_id = c.id
WHERE NOT COALESCE(ucs.suspended, false)
  AND (ucs.buried_until IS NULL OR ucs.buried_until <= ($2::timestamptz)::date)
  AND (ucs.due IS NULL OR ucs.due < $3::timestamptz)
  AND (ucs.last_review IS NULL OR ucs.last_review < $2::timestamptz)
GROUP BY c.deck_id
`

type CountQueueForUserParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	StudyDayStart pgtype.Timestamptz `json:"study_day_start"`
	StudyDayEnd   pgtype.Timestamptz `json:"study_day_end"`
}

type CountQueueForUserRow struct {
	DeckID        pgtype.UUID `json:"deck_id"`
	NewCount      int64       `json:"new_count"`
	LearningCount int64       `json:"learning_count"`
	DueCount      int64       `json:"due_count"`
}

// Same queue summary, grouped by deck, for the /decks list (#80). One query for every deck the
// user can view rather than one CountQueueForDeck call per row.
func (q *Queries) CountQueueForUser(ctx context.Context, arg CountQueueForUserParams) ([]CountQueueForUserRow, error) {
	rows, err := q.db.Query(ctx, countQueueForUser, arg.UserID, arg.StudyDayStart, arg.StudyDayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountQueueForUserRow
	for rows.Next() {
		var i CountQueueForUserRow
		if err := rows.Scan(
			&i.DeckID,
			&i.NewCount,
			&i.LearningCount,
			&i.DueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeckForStudy = `-- name: GetDeckForStudy :one
SELECT d.id, d.owner_id, d.name, d.description, d.preset, d.created_at, d.modified_at, d.anki_id
FROM decks d
JOIN deck_access da ON da.deck_id = d.id AND da.user_id = $1
                   AND da.can_view AND da.can_study
WHERE d.id = $2
`

type GetDeckForStudyParams struct {
	UserID pgtype.UUID `json:"user_id"`
	DeckID pgtype.UUID `json:"deck_id"`
}

func (q *Queries) GetDeckForStudy(ctx context.Context, arg GetDeckForStudyParams) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckForStudy, arg.UserID, arg.DeckID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Preset,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AnkiID,
	)
	return i, err
}

const getStudyDayWindow = `-- name: GetStudyDayWindow :one

WITH l AS (
    SELECT u.timezone AS tz,
           u.day_start_hour::int AS h,
           ($1::timestamptz AT TIME ZONE u.timezone) AS local_now
    FROM users u
    WHERE u.id = $2
), s AS (
    SELECT tz,
           date_trunc('day', local_now - make_interval(hours => h)) + make_interval(hours => h) AS start_local
    FROM l
)
SELECT (start_local AT TIME ZONE tz)::timestamptz                        AS study_day_start,
       ((start_local + interval '1 day') AT TIME ZONE tz)::timestamptz   AS study_day_end
FROM s
`

type GetStudyDayWindowParams struct {
	Now    pgtype.Timestamptz `json:"now"`
	UserID pgtype.UUID        `json:"user_id"`
}

type GetStudyDayWindowRow struct {
	StudyDayStart pgtype.Timestamptz `json:"study_day_start"`
	StudyDayEnd   pgtype.Timestamptz `json:"study_day_end"`
}

// The reviewer's queue (architecture.md §6). Every query here takes user_id and joins deck_access
// (CLAUDE.md §9) -- review routes require can_view AND can_study.
// The day boundary (docs/schema.md): a per-user rollover hour in the user's own timezone, not
// midnight UTC. The arithmetic runs on the LOCAL wall clock, so a DST transition makes the study day
// 23 or 25 hours long instead of silently shifting the rollover. `now` is a parameter, not now(), so
// handler tests can pin the clock.
func (q *Queries) GetStudyDayWindow(ctx context.Context, arg GetStudyDayWindowParams) (GetStudyDayWindowRow, error) {
	row := q.db.QueryRow(ctx, getStudyDayWindow, arg.Now, arg.UserID)
	var i GetStudyDayWindowRow
	err := row.Scan(&i.StudyDayStart, &i.StudyDayEnd)
	return i, err
}

const listDueCardsForStudy = `-- name: ListDueCardsForStudy :many
SELECT c.id                                        AS card_id,
       c.ordinal                                   AS card_ordinal,
       COALESCE(ucs.due, 'infinity'::timestamptz)  AS queue_key,
       (ucs.user_id IS NULL)::boolean              AS unseen,
       COALESCE(ucs.due, now())                    AS due,
       COALESCE(ucs.stability, 0)::double precision  AS stability,
       COALESCE(ucs.difficulty, 0)::double precision AS difficulty,
       COALESCE(ucs.state, 0)::smallint            AS state,
       COALESCE(ucs.reps, 0)::int                  AS reps,
       COALESCE(ucs.lapses, 0)::int                AS lapses,
       COALESCE(ucs.scheduled_days, 0)::int        AS scheduled_days,
       COALESCE(ucs.learning_steps, 0)::smallint   AS learning_steps,
       ucs.last_review                             AS last_review,
       n.fields                                    AS note_fields,
       n.tags                                      AS note_tags,
       nt.id                                       AS note_type_id,
       nt.name                                     AS note_type_name,
       nt.is_cloze                                 AS is_cloze,
       t.name                                      AS template_name,
       t.qfmt                                      AS qfmt,
       t.afmt                                      AS afmt
FROM cards c
JOIN deck_access da ON da.deck_id = c.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_study
JOIN notes n       ON n.id = c.note_id
JOIN note_types nt ON nt.id = n.note_type_id
JOIN templates t   ON t.id = c.template_id
LEFT JOIN user_card_state ucs ON ucs.user_id = $1 AND ucs.card_id = c.id
WHERE c.deck_id = $2
  AND NOT COALESCE(ucs.suspended, false)
  AND (ucs.buried_until IS NULL OR ucs.buried_until <= ($3::timestamptz)::date)
  AND (ucs.due IS NULL OR ucs.due < $4::timestamptz)
  AND (ucs.last_review IS NULL OR ucs.last_review < $3::timestamptz)
  AND (COALESCE(ucs.due, 'infinity'::timestamptz), c.id)
      > ($5::timestamptz, $6::uuid)
ORDER BY queue_key, c.id
LIMIT $7
`

type ListDueCardsForStudyParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	DeckID        pgtype.UUID        `json:"deck_id"`
	StudyDayStart pgtype.Timestamptz `json:"study_day_start"`
	StudyDayEnd   pgtype.Timestamptz `json:"study_day_end"`
	CursorDue     pgtype.Timestamptz `json:"cursor_due"`
	CursorCardID  pgtype.UUID        `json:"cursor_card_id"`
	BatchSize     int32              `json:"batch_size"`
}

type ListDueCardsForStudyRow struct {
	CardID        pgtype.UUID        `json:"card_id"`
	CardOrdinal   int32              `json:"card_ordinal"`
	QueueKey      pgtype.Timestamptz `json:"queue_key"`
	Unseen        bool               `json:"unseen"`
	Due           pgtype.Timestamptz `json:"due"`
	Stability     float64            `json:"stability"`
	Difficulty    float64            `json:"difficulty"`
	State         int16              `json:"state"`
	Reps          int32              `json:"reps"`
	Lapses        int32              `json:"lapses"`
	ScheduledDays int32              `json:"scheduled_days"`
	LearningSteps int16              `json:"learning_steps"`
	LastReview    pgtype.Timestamptz `json:"last_review"`
	NoteFields    []byte             `json:"note_fields"`
	NoteTags      []string           `json:"note_tags"`
	NoteTypeID    pgtype.UUID        `json:"note_type_id"`
	NoteTypeName  string             `json:"note_type_name"`
	IsCloze       bool               `json:"is_cloze"`
	TemplateName  string             `json:"template_name"`
	Qfmt          string             `json:"qfmt"`
	Afmt          string             `json:"afmt"`
}

// The queue. Keyset over (COALESCE(due,'infinity'), card_id): due reviews first by due date, then
// never-seen cards by id. 'infinity' (not NULL) keeps the sort key total -- a NULL inside the row
// comparison below would silently drop every new card from every refill. Never-seen cards have no
// user_card_state row at all, hence the LEFT JOIN and the COALESCEd columns.
func (q *Queries) ListDueCardsForStudy(ctx context.Context, arg ListDueCardsForStudyParams) ([]ListDueCardsForStudyRow, error) {
	rows, err := q.db.Query(ctx, listDueCardsForStudy,
		arg.UserID,
		arg.DeckID,
		arg.StudyDayStart,
		arg.StudyDayEnd,
		arg.CursorDue,
		arg.CursorCardID,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueCardsForStudyRow
	for rows.Next() {
		var i ListDueCardsForStudyRow
		if err := rows.Scan(
			&i.CardID,
			&i.CardOrdinal,
			&i.QueueKey,
			&i.Unseen,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.State,
			&i.Reps,
			&i.Lapses,
			&i.ScheduledDays,
			&i.LearningSteps,
			&i.LastReview,
			&i.NoteFields,
			&i.NoteTags,
			&i.NoteTypeID,
			&i.NoteTypeName,
			&i.IsCloze,
			&i.TemplateName,
			&i.Qfmt,
			&i.Afmt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteTypeCSSForDeck = `-- name: ListNoteTypeCSSForDeck :many
SELECT DISTINCT nt.id, nt.css
FROM cards c
JOIN deck_access da ON da.deck_id = c.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_study
JOIN notes n       ON n.id = c.note_id
JOIN note_types nt ON nt.id = n.note_type_id
WHERE c.deck_id = $2
`

type ListNoteTypeCSSForDeckParams struct {
	UserID pgtype.UUID `json:"user_id"`
	DeckID pgtype.UUID `json:"deck_id"`
}

type ListNoteTypeCSSForDeckRow struct {
	ID  pgtype.UUID `json:"id"`
	Css string      `json:"css"`
}

// Note-type CSS for every card in the deck: sanitised once per page, never per card (#55's doc
// comment), so a refilled card can never arrive before its styles.
func (q *Queries) ListNoteTypeCSSForDeck(ctx context.Context, arg ListNoteTypeCSSForDeckParams) ([]ListNoteTypeCSSForDeckRow, error) {
	rows, err := q.db.Query(ctx, listNoteTypeCSSForDeck, arg.UserID, arg.DeckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNoteTypeCSSForDeckRow
	for rows.Next() {
		var i ListNoteTypeCSSForDeckRow
		if err := rows.Scan(&i.ID, &i.Css); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyableCards = `-- name: ListStudyableCards :many
SELECT c.id AS card_id, c.deck_id
FROM cards c
JOIN deck_access da ON da.deck_id = c.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_study
WHERE c.id = ANY($2::uuid[])
`

type ListStudyableCardsParams struct {
	UserID  pgtype.UUID   `json:"user_id"`
	CardIds []pgtype.UUID `json:"card_ids"`
}

type ListStudyableCardsRow struct {
	CardID pgtype.UUID `json:"card_id"`
	DeckID pgtype.UUID `json:"deck_id"`
}

// Per-card authorisation for a grade batch, which may span decks. A card missing from the result is
// absent, invisible, or not studyable -- deliberately indistinguishable (docs/schema.md).
func (q *Queries) ListStudyableCards(ctx context.Context, arg ListStudyableCardsParams) ([]ListStudyableCardsRow, error) {
	rows, err := q.db.Query(ctx, listStudyableCards, arg.UserID, arg.CardIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudyableCardsRow
	for rows.Next() {
		var i ListStudyableCardsRow
		if err := rows.Scan(&i.CardID, &i.DeckID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCardForGrade = `-- name: LockCardForGrade :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// The per-(user,card) advisory lock, held to commit (architecture.md §6). Advisory rather than
// SELECT ... FOR UPDATE because a never-seen card has no user_card_state row to lock, and two
// concurrent first grades are exactly that case. The key is derived in Go -- see internal/review/
// lock.go for the derivation and for why a batch's keys are acquired in ascending key order.
func (q *Queries) LockCardForGrade(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockCardForGrade, key)
	return err
}
