// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listStatsCardStateForUser = `-- name: ListStatsCardStateForUser :many

SELECT c.deck_id, ucs.stability, ucs.difficulty, ucs.state, ucs.last_review
FROM user_card_state ucs
JOIN cards c ON c.id = ucs.card_id
JOIN deck_access da ON da.deck_id = c.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_study
WHERE ucs.user_id = $1
ORDER BY c.deck_id
`

type ListStatsCardStateForUserRow struct {
	DeckID     pgtype.UUID
	Stability  float64
	Difficulty float64
	State      int16
	LastReview pgtype.Timestamptz
}

// The learner stats page (#261, docs/plans/261-learner-stats-page.md). Every query reads only the
// caller's own user_card_state / review_log rows, restricted to decks the caller holds can_study
// on -- no other user's data is reachable from here, so unlike progress.sql there is no
// can_view_progress exception involved.
// One row per (seen card) across the caller's can_study decks, for the Recall fold in Go. Same
// columns as ListStudentCardStateForDeck (progress.sql), which Recall now must agree with.
func (q *Queries) ListStatsCardStateForUser(ctx context.Context, userID pgtype.UUID) ([]ListStatsCardStateForUserRow, error) {
	rows, err := q.db.Query(ctx, listStatsCardStateForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatsCardStateForUserRow
	for rows.Next() {
		var i ListStatsCardStateForUserRow
		if err := rows.Scan(
			&i.DeckID,
			&i.Stability,
			&i.Difficulty,
			&i.State,
			&i.LastReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatsDailyReviewsForUser = `-- name: ListStatsDailyReviewsForUser :many
SELECT ((rl.reviewed_at AT TIME ZONE u.timezone) - make_interval(hours => u.day_start_hour::int))::date AS day,
       count(*)::bigint                                AS review_count,
       (count(*) FILTER (WHERE rl.rating > 1))::bigint AS pass_count
FROM review_log rl
JOIN users u ON u.id = rl.user_id
JOIN cards c ON c.id = rl.card_id
JOIN deck_access da ON da.deck_id = c.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_study
WHERE rl.user_id = $1
  AND rl.state_before = 2
  AND ((rl.reviewed_at AT TIME ZONE u.timezone) - make_interval(hours => u.day_start_hour::int))::date >= $2::date
GROUP BY 1
ORDER BY 1
`

type ListStatsDailyReviewsForUserParams struct {
	UserID   pgtype.UUID
	FirstDay pgtype.Date
}

type ListStatsDailyReviewsForUserRow struct {
	Day         pgtype.Date
	ReviewCount int64
	PassCount   int64
}

// Overall per-day counts for the two charts, bucketed by the caller's own study day (users.timezone
// and day_start_hour -- the same shift GetStudyDayWindow applies), from first_day onward. Days
// with no reviews have no row; the handler zero-fills them.
func (q *Queries) ListStatsDailyReviewsForUser(ctx context.Context, arg ListStatsDailyReviewsForUserParams) ([]ListStatsDailyReviewsForUserRow, error) {
	rows, err := q.db.Query(ctx, listStatsDailyReviewsForUser, arg.UserID, arg.FirstDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatsDailyReviewsForUserRow
	for rows.Next() {
		var i ListStatsDailyReviewsForUserRow
		if err := rows.Scan(&i.Day, &i.ReviewCount, &i.PassCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatsReviewCountsForUser = `-- name: ListStatsReviewCountsForUser :many
SELECT c.deck_id,
       (count(*) FILTER (WHERE rl.rating > 1))::bigint AS pass_count,
       count(*)::bigint                                AS review_count
FROM review_log rl
JOIN cards c ON c.id = rl.card_id
JOIN deck_access da ON da.deck_id = c.deck_id AND da.user_id = $1
                   AND da.can_view AND da.can_study
WHERE rl.user_id = $1
  AND rl.state_before = 2
  AND rl.reviewed_at >= $2::timestamptz - make_interval(days => $3::int)
GROUP BY c.deck_id
`

type ListStatsReviewCountsForUserParams struct {
	UserID     pgtype.UUID
	Now        pgtype.Timestamptz
	WindowDays int32
}

type ListStatsReviewCountsForUserRow struct {
	DeckID      pgtype.UUID
	PassCount   int64
	ReviewCount int64
}

// Pass rate 30d / Reviews 30d per deck: review-state answers only, the same predicates as the
// reviewstats CTE in ListStudentProgressForDeck (progress.sql).
func (q *Queries) ListStatsReviewCountsForUser(ctx context.Context, arg ListStatsReviewCountsForUserParams) ([]ListStatsReviewCountsForUserRow, error) {
	rows, err := q.db.Query(ctx, listStatsReviewCountsForUser, arg.UserID, arg.Now, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatsReviewCountsForUserRow
	for rows.Next() {
		var i ListStatsReviewCountsForUserRow
		if err := rows.Scan(&i.DeckID, &i.PassCount, &i.ReviewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
