// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (note_type_id, ordinal, name, qfmt, afmt) VALUES ($1,$2,$3,$4,$5) RETURNING id, note_type_id, ordinal, name, qfmt, afmt, browser_qfmt, browser_afmt
`

type CreateTemplateParams struct {
	NoteTypeID pgtype.UUID
	Ordinal    int32
	Name       string
	Qfmt       string
	Afmt       string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.NoteTypeID,
		arg.Ordinal,
		arg.Name,
		arg.Qfmt,
		arg.Afmt,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.NoteTypeID,
		&i.Ordinal,
		&i.Name,
		&i.Qfmt,
		&i.Afmt,
		&i.BrowserQfmt,
		&i.BrowserAfmt,
	)
	return i, err
}

const deleteTemplatesByIDs = `-- name: DeleteTemplatesByIDs :execrows
DELETE FROM templates WHERE note_type_id = $1 AND id = ANY($2::uuid[])
`

type DeleteTemplatesByIDsParams struct {
	NoteTypeID pgtype.UUID
	Ids        []pgtype.UUID
}

// Only safe to call once every card backed by these templates is already gone --
// cards.template_id REFERENCES templates ON DELETE RESTRICT (docs/schema.md's Deletion policy).
// RemapNoteTypeCards (internal/db/cards.go) always calls DeleteCardsForTemplates first.
func (q *Queries) DeleteTemplatesByIDs(ctx context.Context, arg DeleteTemplatesByIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplatesByIDs, arg.NoteTypeID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTemplatesForNoteType = `-- name: ListTemplatesForNoteType :many
SELECT id, note_type_id, ordinal, name, qfmt, afmt, browser_qfmt, browser_afmt FROM templates WHERE note_type_id = $1 ORDER BY ordinal
`

func (q *Queries) ListTemplatesForNoteType(ctx context.Context, noteTypeID pgtype.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesForNoteType, noteTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.NoteTypeID,
			&i.Ordinal,
			&i.Name,
			&i.Qfmt,
			&i.Afmt,
			&i.BrowserQfmt,
			&i.BrowserAfmt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplateContentAndOrdinal = `-- name: UpdateTemplateContentAndOrdinal :execrows
UPDATE templates SET name = $1, qfmt = $2, afmt = $3,
                     ordinal = $4
WHERE id = $5 AND note_type_id = $6
`

type UpdateTemplateContentAndOrdinalParams struct {
	Name       string
	Qfmt       string
	Afmt       string
	Ordinal    int32
	ID         pgtype.UUID
	NoteTypeID pgtype.UUID
}

// Renames/re-formats AND repositions a kept template in one statement (#89), same reasoning as
// UpdateFieldNameAndOrdinal -- templates.ordinal is likewise not UNIQUE-constrained.
func (q *Queries) UpdateTemplateContentAndOrdinal(ctx context.Context, arg UpdateTemplateContentAndOrdinalParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTemplateContentAndOrdinal,
		arg.Name,
		arg.Qfmt,
		arg.Afmt,
		arg.Ordinal,
		arg.ID,
		arg.NoteTypeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
