// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTemplate = `-- name: GetTemplate :one
SELECT id, note_type_id, ordinal, name, qfmt, afmt, browser_qfmt, browser_afmt FROM templates WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id pgtype.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.NoteTypeID,
		&i.Ordinal,
		&i.Name,
		&i.Qfmt,
		&i.Afmt,
		&i.BrowserQfmt,
		&i.BrowserAfmt,
	)
	return i, err
}
