// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_fsrs_params.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeckFsrsRetention = `-- name: GetDeckFsrsRetention :one
SELECT desired_retention FROM user_fsrs_params WHERE user_id = $1 AND deck_id = $2
`

type GetDeckFsrsRetentionParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

func (q *Queries) GetDeckFsrsRetention(ctx context.Context, arg GetDeckFsrsRetentionParams) (float64, error) {
	row := q.db.QueryRow(ctx, getDeckFsrsRetention, arg.UserID, arg.DeckID)
	var desired_retention float64
	err := row.Scan(&desired_retention)
	return desired_retention, err
}

const getEffectiveFsrsParams = `-- name: GetEffectiveFsrsParams :one
SELECT fsrs_version, params, desired_retention
FROM user_fsrs_params
WHERE user_id = $1 AND (deck_id = $2 OR deck_id IS NULL)
ORDER BY deck_id NULLS LAST
LIMIT 1
`

type GetEffectiveFsrsParamsParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

type GetEffectiveFsrsParamsRow struct {
	FsrsVersion      int16
	Params           []byte
	DesiredRetention float64
}

// The per-(user,deck) override if there is one, else the user's global row. deck_id NULLS LAST puts
// the override first (CLAUDE.md §2.3, §2.4: never one parameter set across a cohort).
func (q *Queries) GetEffectiveFsrsParams(ctx context.Context, arg GetEffectiveFsrsParamsParams) (GetEffectiveFsrsParamsRow, error) {
	row := q.db.QueryRow(ctx, getEffectiveFsrsParams, arg.UserID, arg.DeckID)
	var i GetEffectiveFsrsParamsRow
	err := row.Scan(&i.FsrsVersion, &i.Params, &i.DesiredRetention)
	return i, err
}

const getEffectiveFsrsParamsForUsers = `-- name: GetEffectiveFsrsParamsForUsers :many
SELECT DISTINCT ON (user_id) user_id, fsrs_version, params, desired_retention
FROM user_fsrs_params
WHERE user_id = ANY($1::uuid[]) AND (deck_id = $2 OR deck_id IS NULL)
ORDER BY user_id, deck_id NULLS LAST
`

type GetEffectiveFsrsParamsForUsersParams struct {
	UserIds []pgtype.UUID
	DeckID  pgtype.UUID
}

type GetEffectiveFsrsParamsForUsersRow struct {
	UserID           pgtype.UUID
	FsrsVersion      int16
	Params           []byte
	DesiredRetention float64
}

// Batched form of GetEffectiveFsrsParams for a page of users on one deck (#87's instructor
// dashboard): one round trip instead of one query per student. DISTINCT ON keeps the
// highest-priority row per user -- same deck_id NULLS LAST precedence as above, applied per user
// rather than per single arg. A user with neither a per-deck override nor a global row is simply
// absent from the result; the caller falls back to library defaults for them, same as
// GetEffectiveFsrsParams's pgx.ErrNoRows case.
func (q *Queries) GetEffectiveFsrsParamsForUsers(ctx context.Context, arg GetEffectiveFsrsParamsForUsersParams) ([]GetEffectiveFsrsParamsForUsersRow, error) {
	rows, err := q.db.Query(ctx, getEffectiveFsrsParamsForUsers, arg.UserIds, arg.DeckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEffectiveFsrsParamsForUsersRow
	for rows.Next() {
		var i GetEffectiveFsrsParamsForUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.FsrsVersion,
			&i.Params,
			&i.DesiredRetention,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalFsrsRetention = `-- name: GetGlobalFsrsRetention :one
SELECT desired_retention FROM user_fsrs_params WHERE user_id = $1 AND deck_id IS NULL
`

func (q *Queries) GetGlobalFsrsRetention(ctx context.Context, userID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getGlobalFsrsRetention, userID)
	var desired_retention float64
	err := row.Scan(&desired_retention)
	return desired_retention, err
}

const getUserFsrsParams = `-- name: GetUserFsrsParams :one
SELECT id, user_id, deck_id, fsrs_version, params, desired_retention, optimised_at, review_count_at_fit FROM user_fsrs_params WHERE id = $1
`

func (q *Queries) GetUserFsrsParams(ctx context.Context, id pgtype.UUID) (UserFsrsParam, error) {
	row := q.db.QueryRow(ctx, getUserFsrsParams, id)
	var i UserFsrsParam
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.FsrsVersion,
		&i.Params,
		&i.DesiredRetention,
		&i.OptimisedAt,
		&i.ReviewCountAtFit,
	)
	return i, err
}

const seedDeckFsrsRetention = `-- name: SeedDeckFsrsRetention :exec
INSERT INTO user_fsrs_params (user_id, deck_id, fsrs_version, params, desired_retention)
SELECT $1, $2, $3, '[]'::jsonb, $4
FROM deck_access da
WHERE da.deck_id = $2 AND da.user_id = $1 AND da.can_view AND da.can_study
ON CONFLICT (user_id, deck_id) DO NOTHING
`

type SeedDeckFsrsRetentionParams struct {
	UserID           pgtype.UUID
	DeckID           pgtype.UUID
	FsrsVersion      int16
	DesiredRetention float64
}

// Seeds a deck's desired retention from an apkg import, first-import-only: DO NOTHING on
// conflict so a re-import never clobbers a retention the user has since changed themselves.
func (q *Queries) SeedDeckFsrsRetention(ctx context.Context, arg SeedDeckFsrsRetentionParams) error {
	_, err := q.db.Exec(ctx, seedDeckFsrsRetention,
		arg.UserID,
		arg.DeckID,
		arg.FsrsVersion,
		arg.DesiredRetention,
	)
	return err
}

const upsertDeckFsrsRetention = `-- name: UpsertDeckFsrsRetention :execrows
INSERT INTO user_fsrs_params (user_id, deck_id, fsrs_version, params, desired_retention)
SELECT $1, $2, $3, '[]'::jsonb, $4
FROM deck_access da
WHERE da.deck_id = $2 AND da.user_id = $1 AND da.can_view AND da.can_study
ON CONFLICT (user_id, deck_id)
DO UPDATE SET fsrs_version = EXCLUDED.fsrs_version, desired_retention = EXCLUDED.desired_retention
`

type UpsertDeckFsrsRetentionParams struct {
	UserID           pgtype.UUID
	DeckID           pgtype.UUID
	FsrsVersion      int16
	DesiredRetention float64
}

// Authorisation lives in the SELECT source, not a handler guard (CLAUDE.md §9): a caller
// without can_view+can_study on the deck matches zero deck_access rows, so the INSERT touches
// nothing and :execrows reports 0 -- the same "0 rows = not found" shape POST /decks/{id}/edit
// uses (decks.sql UpdateDeck).
func (q *Queries) UpsertDeckFsrsRetention(ctx context.Context, arg UpsertDeckFsrsRetentionParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertDeckFsrsRetention,
		arg.UserID,
		arg.DeckID,
		arg.FsrsVersion,
		arg.DesiredRetention,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertGlobalFsrsRetention = `-- name: UpsertGlobalFsrsRetention :exec
INSERT INTO user_fsrs_params (user_id, deck_id, fsrs_version, params, desired_retention)
VALUES ($1, NULL, $2, '[]'::jsonb, $3)
ON CONFLICT (user_id) WHERE deck_id IS NULL
DO UPDATE SET fsrs_version = EXCLUDED.fsrs_version, desired_retention = EXCLUDED.desired_retention
`

type UpsertGlobalFsrsRetentionParams struct {
	UserID           pgtype.UUID
	FsrsVersion      int16
	DesiredRetention float64
}

// Global row upsert targets the partial unique index (migration 00012:
// user_fsrs_params_user_id_global_key) -- the plain (user_id, deck_id) index does not enforce
// "one global row per user" because NULLs never conflict against each other in a btree unique
// index, which is exactly why that second, partial index exists.
func (q *Queries) UpsertGlobalFsrsRetention(ctx context.Context, arg UpsertGlobalFsrsRetentionParams) error {
	_, err := q.db.Exec(ctx, upsertGlobalFsrsRetention, arg.UserID, arg.FsrsVersion, arg.DesiredRetention)
	return err
}
