// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_fsrs_params.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserFsrsParams = `-- name: GetUserFsrsParams :one
SELECT id, user_id, deck_id, fsrs_version, params, desired_retention, optimised_at, review_count_at_fit FROM user_fsrs_params WHERE id = $1
`

func (q *Queries) GetUserFsrsParams(ctx context.Context, id pgtype.UUID) (UserFsrsParam, error) {
	row := q.db.QueryRow(ctx, getUserFsrsParams, id)
	var i UserFsrsParam
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.FsrsVersion,
		&i.Params,
		&i.DesiredRetention,
		&i.OptimisedAt,
		&i.ReviewCountAtFit,
	)
	return i, err
}
