// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_card_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserCardState = `-- name: GetUserCardState :one
SELECT user_id, card_id, due, stability, difficulty, state, reps, lapses, elapsed_days, scheduled_days, learning_steps, last_review, suspended, buried_until, flag FROM user_card_state WHERE user_id = $1 AND card_id = $2
`

type GetUserCardStateParams struct {
	UserID pgtype.UUID `json:"user_id"`
	CardID pgtype.UUID `json:"card_id"`
}

func (q *Queries) GetUserCardState(ctx context.Context, arg GetUserCardStateParams) (UserCardState, error) {
	row := q.db.QueryRow(ctx, getUserCardState, arg.UserID, arg.CardID)
	var i UserCardState
	err := row.Scan(
		&i.UserID,
		&i.CardID,
		&i.Due,
		&i.Stability,
		&i.Difficulty,
		&i.State,
		&i.Reps,
		&i.Lapses,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.LearningSteps,
		&i.LastReview,
		&i.Suspended,
		&i.BuriedUntil,
		&i.Flag,
	)
	return i, err
}
